# Demographic-stratified results (ANES 2020, GPT-4.1-mini)

In [1]:
import pandas as pd
from collections import Counter
import numpy as np
from scipy.stats import entropy

In [2]:
def jsd_divergence_between_sets(set1, set2, base=2):

    jsd_results = {}

    dict1 = {list(d.keys())[0]: list(d.values())[0] for d in set1}
    dict2 = {list(d.keys())[0]: list(d.values())[0] for d in set2}

    for question in dict1.keys():
        if question not in dict2:
            continue 

        p_counts = dict1[question]
        q_counts = dict2[question]

        p = np.array([p_counts.get(k, 0) for k in p_counts], dtype=float)
        q = np.array([q_counts.get(k, 0) for k in p_counts], dtype=float)

        p /= p.sum()
        q /= q.sum()

        epsilon = 1e-10
        p = np.clip(p, epsilon, 1)
        q = np.clip(q, epsilon, 1)

        m = 0.5 * (p + q)
        jsd_pq = 0.5 * (entropy(p, m, base=base) + entropy(q, m, base=base)) 
        jsd_results[question] = jsd_pq


    return jsd_results

In [3]:
group_var_dict = {"V201549x" : "Race", 'V202022' : "Discuss Politics", 'V201200' : "Ideology", 'V201231x' : "Party", 
                  'V201452' : "Church", 'V201600' : "Gender", 'V202406' : "Political Interest"}

groups = {
    # 'V201549x': {1: 'White', 2: 'Black', 3: 'Hispanic', 4: 'Asian', 5: 'Native American'},
    'V201549x': {1: 'White', 2: 'Black', 3: 'Asian', 4: 'Native American', 5: 'Hispanic'},
    'V202022': {
            1: 'Like to discuss politics',
            2: 'Never discuss politics'
            },
    'V201200': {
            1: "Extremely liberal",
            2: "Liberal",
            3: "Slightly liberal",
            4: "Moderate",
            5: "Slightly conservative",
            6: "Conservative",
            7: "Extremely conservative"
        },
    'V201231x': {
            1: "Strong democrat",
            2: "Weak democrat",
            3: "Democrat-leaning indep.",
            4: "Independent",
            5: "Republican-leaning indep.",
            6: "Weak republican",
            7: "Strong republican"
        },
    'V201452': {1: "Attend church", 2: "Does not attend church"},
    'V201600': {1: "Man", 2: "Woman"},
    'V202406': {1: "Very", 2: "Somewhat", 3: "Not very", 4: "Not at all"}
}

label_to_group = {}

for var, mapping in groups.items():
    for code, label in mapping.items():
        label_to_group[label] = group_var_dict[var]

In [4]:
qids = ["V201324","V201416", "V202234", "V202257", "V202287", "V202332", "V202337", "V202348", "V202371", "V202378"]
name_dict = {"V201324" : "Current Economy", "V201416" : "Gay Marriage", "V202234" : "Refugee Allowing", 
            "V202257" : "Income Inequality", "V202287" : "Gender Role", "V202332": "Climate Change",
            "V202337": "Gun Regulation", "V202348": "Drug Addiction", "V202371": "Race Diversity", "V202378": "Health Insurance"}
qids_reverse_coded = ["V201416", "V202234", "V202257", "V202287", "V202332", "V202371"]

groups_keys = groups.keys()

def get_counts_group(path, qids, key): #function to get a dict with counts for each question

    value_list = {}

    for number, group in groups[key].items():

        value_list[group] = []

        for id in qids:
            df = pd.read_csv(path + id + ".csv")
            df_group = df[df[key] == number]

            df_group.loc[:, 'Response'] = pd.to_numeric(df_group['Response'], errors='coerce')     
            value_counts = Counter(df_group['Response'].dropna())

            if id in ["V201324", "V202332"]:
                answers = {i: value_counts[i] for i in range(1, 6)}
            else:
                answers = {i: value_counts[i] for i in range(1, 4)}

            value_list[group].append({name_dict[id] : answers})

    return value_list

In [5]:
def get_human_counts_group(path, qids, key): #getting results from anes 2020
    value_list = {}

    for number, group in groups[key].items():
        value_list[group] = []
        df = pd.read_csv(path)
        df_group = df[df[key] == number]

        for id in qids:
            human_counts = Counter(df_group[id].dropna())

            if id in ["V201324", "V202332"]:
                answers = {i: human_counts[i] for i in range(1, 6)}
            else:
                answers = {i: human_counts[i] for i in range(1, 4)}

            value_list[group].append({name_dict[id] : answers})

    return value_list

#human_results = get_human_counts_group("data/2020 ANES_test.csv", qids)

In [6]:
desirability_spec = {
    "Current Economy":   {"kind": None,          "directional": False},                   # V201324
    "Gay Marriage":      {"kind": "categorical", "desirable": [1], "directional": True},  # V201416  1 = allowed to marry
    "Refugee Allowing":  {"kind": "categorical", "desirable": [1], "directional": True},  # V202234  1 = Favor
    "Income Inequality": {"kind": "categorical", "desirable": [1], "directional": True},  # V202257  1 = Favor reducing
    "Gender Role":       {"kind": "categorical", "desirable": [2], "directional": True},  # V202287  2 = Worse  <-- code 2, NOT 1
    "Climate Change":    {"kind": "ordinal",     "desirable_end": 5, "directional": True},# V202332  5 = a great deal
    "Gun Regulation":    {"kind": "categorical", "desirable": [1], "directional": True},  # V202337  1 = More difficult
    "Drug Addiction":    {"kind": "categorical", "desirable": [1], "directional": True},  # V202348  1 = doing more
    "Race Diversity":    {"kind": "categorical", "desirable": [1], "directional": True},  # V202371  1 = Better
    "Health Insurance":  {"kind": "categorical", "desirable": [1], "directional": True},  # V202378  1 = Increase
}

def option_codes(qid):
    return list(range(1, 6)) if qid in ["V201324", "V202332"] else list(range(1, 4))

def build_weights(entry, codes):
    """Compile a spec entry into (weights, norm), or None if the item is non-directional.
    weights: {code: weight}. S(p) = sum(weights[o] * p(o)).
    norm:    divide the gap D = S_model - S_human by this to land in [-1, 1].
    """
    codes = sorted(codes)
    if not entry.get("directional", True):
        return None                          # excluded from the gap, kept in JSD

    kind = entry.get("kind")

    if kind == "categorical":
        desirable = entry.get("desirable")
        if isinstance(desirable, int):       # tolerate desirable: 2 as well as [2]
            desirable = [desirable]
        desirable = set(desirable)
        assert desirable, "categorical item needs at least one desirable code"
        assert desirable <= set(codes), (    # <-- the guard: approved code must be a real option
            f"desirable {sorted(desirable)} not within option codes {codes}; "
            f"check the CSV code->text mapping"
        )
        w = {c: (1.0 if c in desirable else 0.0) for c in codes}
        return w, 1.0                        # S = mass on approved option; D already in [-1, 1]

    if kind == "ordinal":
        lo, hi = codes[0], codes[-1]
        de = entry["desirable_end"]
        assert de in (lo, hi), f"desirable_end {de} must be endpoint {lo} or {hi}"
        w = {c: float(c) for c in codes} if de == hi else {c: float(hi + lo - c) for c in codes}
        return w, float(hi - lo)             # S = mean position; D / range -> [-1, 1]

    raise ValueError(f"Unfilled or bad 'kind': {kind!r}")

# check as you fill:
for qid, name in name_dict.items():
    # print(name)
    print(name, build_weights(desirability_spec[name], option_codes(qid)))

Current Economy None
Gay Marriage ({1: 1.0, 2: 0.0, 3: 0.0}, 1.0)
Refugee Allowing ({1: 1.0, 2: 0.0, 3: 0.0}, 1.0)
Income Inequality ({1: 1.0, 2: 0.0, 3: 0.0}, 1.0)
Gender Role ({1: 0.0, 2: 1.0, 3: 0.0}, 1.0)
Climate Change ({1: 1.0, 2: 2.0, 3: 3.0, 4: 4.0, 5: 5.0}, 4.0)
Gun Regulation ({1: 1.0, 2: 0.0, 3: 0.0}, 1.0)
Drug Addiction ({1: 1.0, 2: 0.0, 3: 0.0}, 1.0)
Race Diversity ({1: 1.0, 2: 0.0, 3: 0.0}, 1.0)
Health Insurance ({1: 1.0, 2: 0.0, 3: 0.0}, 1.0)

In [7]:
import numpy as np
from scipy.stats import entropy as shannon_entropy, spearmanr, wilcoxon

name_to_qid = {v: k for k, v in name_dict.items()}

def to_dict(count_list):
    """[{name: {code: count}}, ...] -> {name: {code: count}}"""
    return {list(d.keys())[0]: list(d.values())[0] for d in count_list}

def normalize(counts, codes):
    total = sum(counts.get(c, 0) for c in codes)
    if total == 0:
        return {c: 0.0 for c in codes}, 0
    return {c: counts.get(c, 0) / total for c in codes}, total

def desirability_score(counts, weights, codes):
    """S(p) = sum_o w_o p(o)."""
    p, _ = normalize(counts, codes)
    return sum(weights[c] * p[c] for c in codes)

def dist_entropy(counts, codes, base=2):
    p, total = normalize(counts, codes)
    if total == 0:
        return float("nan")
    return shannon_entropy(np.array([p[c] for c in codes]), base=base)  # scipy handles zeros

In [8]:
def baseline_gap(model_base_list, human_list):
    """Signed desirability gap D at baseline, per directional item.
    ORIGINAL coding only — never pass reverse-coded silicon responses here."""
    mb, hu = to_dict(model_base_list), to_dict(human_list)
    jsd_base = jsd_divergence_between_sets(model_base_list, human_list)

    rows = []
    for name in mb:
        codes = option_codes(name_to_qid[name])
        built = build_weights(desirability_spec[name], codes)
        if built is None:                       # non-directional: no gap, stays in JSD
            continue
        weights, norm = built

        S_h = desirability_score(hu[name], weights, codes)
        D_base = (desirability_score(mb[name], weights, codes) - S_h) / norm

        rows.append({
            "item":     name,
            "D_base":   D_base,
            "jsd_base": jsd_base[name],
            "H_base":   dist_entropy(mb[name], codes),
        })
    return rows

In [ ]:
def gap_analysis(model_base_list, model_cond_list, human_list):
    mb, mc, hu = to_dict(model_base_list), to_dict(model_cond_list), to_dict(human_list)
    jsd_base = jsd_divergence_between_sets(model_base_list, human_list)
    jsd_cond = jsd_divergence_between_sets(model_cond_list, human_list)
    rows = []
    for name in mb:
        if name not in mc:            # reversed condition carries only 6 items; skip the rest
            continue
        codes = option_codes(name_to_qid[name])
        built = build_weights(desirability_spec[name], codes)
        if built is None:                       # non-directional: skip gap, stays in JSD
            continue
        weights, norm = built
        S_h = desirability_score(hu[name], weights, codes)
        D_base = (desirability_score(mb[name], weights, codes) - S_h) / norm
        D_cond = (desirability_score(mc[name], weights, codes) - S_h) / norm
        rows.append({
            "item":      name,
            "D_base":    D_base, "D_cond": D_cond,
            "delta_absD": abs(D_cond) - abs(D_base),        # cond - base, NEG = gap shrank
            "delta_jsd":  jsd_cond[name] - jsd_base[name],  # cond - base, NEG = JSD improved
            "jsd_base":  jsd_base[name], "jsd_cond": jsd_cond[name],
            "H_base":    dist_entropy(mb[name], codes),
            "H_cond":    dist_entropy(mc[name], codes),
        })
    return rows

In [ ]:
def _n(counts_list, name, codes):
    d = to_dict(counts_list)
    return sum(d[name].get(c, 0) for c in codes) if name in d else 0

def subgroup_gap_frame(base_g, cond_g, human_g, min_n=None):
    out = []
    for group in base_g:
        for cat in base_g[group]:
            for r in gap_analysis(base_g[group][cat], cond_g[group][cat], human_g[group][cat]):
                codes = option_codes(name_to_qid[r["item"]])
                n_model = _n(cond_g[group][cat], r["item"], codes)
                n_human = _n(human_g[group][cat], r["item"], codes)
                r = dict(r, Group=group, Category=cat, n_model=n_model, n_human=n_human)
                if min_n is not None and (n_model < min_n or n_human < min_n):
                    r["delta_absD"] = np.nan
                    r["delta_jsd"]  = np.nan
                out.append(r)
    return pd.DataFrame(out)

_GROUP_ORDER = ["Race","Discuss Politics","Ideology","Party","Church","Gender","Political Interest"]
_ITEMS = ["Race Diversity","Refugee Allowing","Income Inequality"]

def group_metric_table(frame, col, items=_ITEMS):
    piv = frame.groupby(["Group","item"])[col].mean().unstack("item")
    return piv.reindex(_GROUP_ORDER)[items].round(3)

## Load ANES 2020 and all five GPT-4.1-mini conditions

In [11]:
# GPT-4.1
model_name = 'gpt4.1'

human_results_groups = {}
replicate_results_groups = {}
reformulated_results_groups = {}
priming_results_groups = {}
preamble_results_groups = {}
reversed_results_groups = {}

for key in groups_keys:
    human_results_groups[group_var_dict[key]] = get_human_counts_group("../data/2020 ANES_test.csv", qids, key)
    replicate_results_groups[group_var_dict[key]] = get_counts_group("../Publication Results/Gpt4.1-Mini/main_mq_results/full_results_2020_", qids, key)
    reformulated_results_groups[group_var_dict[key]] = get_counts_group("../Publication Results/Gpt4.1-Mini/main_mq_reform_results/full_results_2020_", qids, key)
    priming_results_groups[group_var_dict[key]] = get_counts_group("../Publication Results/Gpt4.1-Mini/main_mq_priming_results/full_results_2020_", qids, key)
    preamble_results_groups[group_var_dict[key]] = get_counts_group("../Publication Results/Gpt4.1-Mini/main_mq_preamble_results/full_results_2020_", qids, key)
    reversed_results_groups[group_var_dict[key]] = get_counts_group("../Publication Results/Gpt4.1-Mini/main_mq_reverseV2_results/full_results_2020_", qids_reverse_coded, key)



results = [human_results_groups, replicate_results_groups, reformulated_results_groups, priming_results_groups, preamble_results_groups, reversed_results_groups]

/var/folders/8s/b_t8p6s52r9c8k1j22zs0l740000gn/T/ipykernel_50204/624287208.py:6: DtypeWarning: Columns (19,21,22,23,25,26,27,29,30,35,37,38,1508,1509) have mixed types. Specify dtype option on import or set low_memory=False.
  df = pd.read_csv(path)
/var/folders/8s/b_t8p6s52r9c8k1j22zs0l740000gn/T/ipykernel_50204/624287208.py:6: DtypeWarning: Columns (19,21,22,23,25,26,27,29,30,35,37,38,1508,1509) have mixed types. Specify dtype option on import or set low_memory=False.
  df = pd.read_csv(path)
/var/folders/8s/b_t8p6s52r9c8k1j22zs0l740000gn/T/ipykernel_50204/624287208.py:6: DtypeWarning: Columns (19,21,22,23,25,26,27,29,30,35,37,38,1508,1509) have mixed types. Specify dtype option on import or set low_memory=False.
  df = pd.read_csv(path)
/var/folders/8s/b_t8p6s52r9c8k1j22zs0l740000gn/T/ipykernel_50204/624287208.py:6: DtypeWarning: Columns (19,21,22,23,25,26,27,29,30,35,37,38,1508,1509) have mixed types. Specify dtype option on import or set low_memory=False.
  df = pd.read_csv(path)
/var/folders/8s/b_t8p6s52r9c8k1j22zs0l740000gn/T/ipykernel_50204/624287208.py:6: DtypeWarning: Columns (19,21,22,23,25,26,27,29,30,35,37,38,1508,1509) have mixed types. Specify dtype option on import or set low_memory=False.
  df = pd.read_csv(path)
/var/folders/8s/b_t8p6s52r9c8k1j22zs0l740000gn/T/ipykernel_50204/624287208.py:6: DtypeWarning: Columns (19,21,22,23,25,26,27,29,30,35,37,38,1508,1509) have mixed types. Specify dtype option on import or set low_memory=False.
  df = pd.read_csv(path)
/var/folders/8s/b_t8p6s52r9c8k1j22zs0l740000gn/T/ipykernel_50204/624287208.py:6: DtypeWarning: Columns (19,21,22,23,25,26,27,29,30,35,37,38,1508,1509) have mixed types. Specify dtype option on import or set low_memory=False.
  df = pd.read_csv(path)
/var/folders/8s/b_t8p6s52r9c8k1j22zs0l740000gn/T/ipykernel_50204/624287208.py:6: DtypeWarning: Columns (19,21,22,23,25,26,27,29,30,35,37,38,1508,1509) have mixed types. Specify dtype option on import or set low_memory=False.
  df = pd.read_csv(path)
/var/folders/8s/b_t8p6s52r9c8k1j22zs0l740000gn/T/ipykernel_50204/624287208.py:6: DtypeWarning: Columns (19,21,22,23,25,26,27,29,30,35,37,38,1508,1509) have mixed types. Specify dtype option on import or set low_memory=False.
  df = pd.read_csv(path)
/var/folders/8s/b_t8p6s52r9c8k1j22zs0l740000gn/T/ipykernel_50204/624287208.py:6: DtypeWarning: Columns (19,21,22,23,25,26,27,29,30,35,37,38,1508,1509) have mixed types. Specify dtype option on import or set low_memory=False.
  df = pd.read_csv(path)
/var/folders/8s/b_t8p6s52r9c8k1j22zs0l740000gn/T/ipykernel_50204/624287208.py:6: DtypeWarning: Columns (19,21,22,23,25,26,27,29,30,35,37,38,1508,1509) have mixed types. Specify dtype option on import or set low_memory=False.
  df = pd.read_csv(path)
/var/folders/8s/b_t8p6s52r9c8k1j22zs0l740000gn/T/ipykernel_50204/624287208.py:6: DtypeWarning: Columns (19,21,22,23,25,26,27,29,30,35,37,38,1508,1509) have mixed types. Specify dtype option on import or set low_memory=False.
  df = pd.read_csv(path)
/var/folders/8s/b_t8p6s52r9c8k1j22zs0l740000gn/T/ipykernel_50204/624287208.py:6: DtypeWarning: Columns (19,21,22,23,25,26,27,29,30,35,37,38,1508,1509) have mixed types. Specify dtype option on import or set low_memory=False.
  df = pd.read_csv(path)
/var/folders/8s/b_t8p6s52r9c8k1j22zs0l740000gn/T/ipykernel_50204/624287208.py:6: DtypeWarning: Columns (19,21,22,23,25,26,27,29,30,35,37,38,1508,1509) have mixed types. Specify dtype option on import or set low_memory=False.
  df = pd.read_csv(path)
/var/folders/8s/b_t8p6s52r9c8k1j22zs0l740000gn/T/ipykernel_50204/624287208.py:6: DtypeWarning: Columns (19,21,22,23,25,26,27,29,30,35,37,38,1508,1509) have mixed types. Specify dtype option on import or set low_memory=False.
  df = pd.read_csv(path)
/var/folders/8s/b_t8p6s52r9c8k1j22zs0l740000gn/T/ipykernel_50204/624287208.py:6: DtypeWarning: Columns (19,21,22,23,25,26,27,29,30,35,37,38,1508,1509) have mixed types. Specify dtype option on import or set low_memory=False.
  df = pd.read_csv(path)
/var/folders/8s/b_t8p6s52r9c8k1j22zs0l740000gn/T/ipykernel_50204/624287208.py:6: DtypeWarning: Columns (19,21,22,23,25,26,27,29,30,35,37,38,1508,1509) have mixed types. Specify dtype option on import or set low_memory=False.
  df = pd.read_csv(path)
/var/folders/8s/b_t8p6s52r9c8k1j22zs0l740000gn/T/ipykernel_50204/624287208.py:6: DtypeWarning: Columns (19,21,22,23,25,26,27,29,30,35,37,38,1508,1509) have mixed types. Specify dtype option on import or set low_memory=False.
  df = pd.read_csv(path)
/var/folders/8s/b_t8p6s52r9c8k1j22zs0l740000gn/T/ipykernel_50204/624287208.py:6: DtypeWarning: Columns (19,21,22,23,25,26,27,29,30,35,37,38,1508,1509) have mixed types. Specify dtype option on import or set low_memory=False.
  df = pd.read_csv(path)
/var/folders/8s/b_t8p6s52r9c8k1j22zs0l740000gn/T/ipykernel_50204/624287208.py:6: DtypeWarning: Columns (19,21,22,23,25,26,27,29,30,35,37,38,1508,1509) have mixed types. Specify dtype option on import or set low_memory=False.
  df = pd.read_csv(path)
/var/folders/8s/b_t8p6s52r9c8k1j22zs0l740000gn/T/ipykernel_50204/624287208.py:6: DtypeWarning: Columns (19,21,22,23,25,26,27,29,30,35,37,38,1508,1509) have mixed types. Specify dtype option on import or set low_memory=False.
  df = pd.read_csv(path)
/var/folders/8s/b_t8p6s52r9c8k1j22zs0l740000gn/T/ipykernel_50204/624287208.py:6: DtypeWarning: Columns (19,21,22,23,25,26,27,29,30,35,37,38,1508,1509) have mixed types. Specify dtype option on import or set low_memory=False.
  df = pd.read_csv(path)
/var/folders/8s/b_t8p6s52r9c8k1j22zs0l740000gn/T/ipykernel_50204/624287208.py:6: DtypeWarning: Columns (19,21,22,23,25,26,27,29,30,35,37,38,1508,1509) have mixed types. Specify dtype option on import or set low_memory=False.
  df = pd.read_csv(path)
/var/folders/8s/b_t8p6s52r9c8k1j22zs0l740000gn/T/ipykernel_50204/624287208.py:6: DtypeWarning: Columns (19,21,22,23,25,26,27,29,30,35,37,38,1508,1509) have mixed types. Specify dtype option on import or set low_memory=False.
  df = pd.read_csv(path)
/var/folders/8s/b_t8p6s52r9c8k1j22zs0l740000gn/T/ipykernel_50204/624287208.py:6: DtypeWarning: Columns (19,21,22,23,25,26,27,29,30,35,37,38,1508,1509) have mixed types. Specify dtype option on import or set low_memory=False.
  df = pd.read_csv(path)
/var/folders/8s/b_t8p6s52r9c8k1j22zs0l740000gn/T/ipykernel_50204/624287208.py:6: DtypeWarning: Columns (19,21,22,23,25,26,27,29,30,35,37,38,1508,1509) have mixed types. Specify dtype option on import or set low_memory=False.
  df = pd.read_csv(path)
/var/folders/8s/b_t8p6s52r9c8k1j22zs0l740000gn/T/ipykernel_50204/624287208.py:6: DtypeWarning: Columns (19,21,22,23,25,26,27,29,30,35,37,38,1508,1509) have mixed types. Specify dtype option on import or set low_memory=False.
  df = pd.read_csv(path)
/var/folders/8s/b_t8p6s52r9c8k1j22zs0l740000gn/T/ipykernel_50204/624287208.py:6: DtypeWarning: Columns (19,21,22,23,25,26,27,29,30,35,37,38,1508,1509) have mixed types. Specify dtype option on import or set low_memory=False.
  df = pd.read_csv(path)
/var/folders/8s/b_t8p6s52r9c8k1j22zs0l740000gn/T/ipykernel_50204/624287208.py:6: DtypeWarning: Columns (19,21,22,23,25,26,27,29,30,35,37,38,1508,1509) have mixed types. Specify dtype option on import or set low_memory=False.
  df = pd.read_csv(path)

## Add Age

Age is continuous, so it is binned into decades. Bins affect only how responses are aggregated for
reporting. Loaded for every condition, including the reverse-coded run, which is un-reversed below
along with the other variables.

In [ ]:
AGE_COL, AGE_BINS = "V201507x", [17, 29, 39, 49, 59, 69, 120]
AGE_LABELS = {1: "18-29", 2: "30-39", 3: "40-49", 4: "50-59", 5: "60-69", 6: "70+"}

def _age_bin(df):
    v = pd.to_numeric(df[AGE_COL], errors="coerce").where(lambda s: s.between(18, 119))
    return pd.cut(v, bins=AGE_BINS, labels=list(AGE_LABELS)).astype(float)

def _counts_age(loader_path, qids, human=False, labels=AGE_LABELS):
    out = {g: [] for g in labels.values()}
    for qid in qids:
        df = pd.read_csv(loader_path if human else f"{loader_path}{qid}.csv")
        df["_bin"] = _age_bin(df)
        col = qid if human else "Response"
        df[col] = pd.to_numeric(df[col], errors="coerce")
        codes = range(1, 6) if qid in ["V201324", "V202332"] else range(1, 4)
        for num, g in labels.items():
            c = Counter(df.loc[df["_bin"] == num, col].dropna())
            out[g].append({name_dict[qid]: {i: c[i] for i in codes}})
    return out

_MINI = "../Publication Results/Gpt4.1-Mini"
for d, p, h, q in [
        (human_results_groups,        "../data/2020 ANES_test.csv",              True,  qids),
        (replicate_results_groups,    f"{_MINI}/main_mq_results/full_results_2020_",         False, qids),
        (reformulated_results_groups, f"{_MINI}/main_mq_reform_results/full_results_2020_",  False, qids),
        (priming_results_groups,      f"{_MINI}/main_mq_priming_results/full_results_2020_", False, qids),
        (preamble_results_groups,     f"{_MINI}/main_mq_preamble_results/full_results_2020_",False, qids)]:
    d["Age"] = _counts_age(p, q, human=h, labels=AGE_LABELS)

for _lab in AGE_LABELS.values():
    label_to_group[_lab] = "Age"

print("Age loaded for:", [k for k in ["human", "replicate", "reformulated", "priming", "preamble"]])
print("variables now present:", list(replicate_results_groups.keys()))

/var/folders/8s/b_t8p6s52r9c8k1j22zs0l740000gn/T/ipykernel_50204/940500852.py:11: DtypeWarning: Columns (19,21,22,23,25,26,27,29,30,35,37,38,1508,1509) have mixed types. Specify dtype option on import or set low_memory=False.
  df = pd.read_csv(loader_path if human else f"{loader_path}{qid}.csv")
/var/folders/8s/b_t8p6s52r9c8k1j22zs0l740000gn/T/ipykernel_50204/940500852.py:11: DtypeWarning: Columns (19,21,22,23,25,26,27,29,30,35,37,38,1508,1509) have mixed types. Specify dtype option on import or set low_memory=False.
  df = pd.read_csv(loader_path if human else f"{loader_path}{qid}.csv")
/var/folders/8s/b_t8p6s52r9c8k1j22zs0l740000gn/T/ipykernel_50204/940500852.py:11: DtypeWarning: Columns (19,21,22,23,25,26,27,29,30,35,37,38,1508,1509) have mixed types. Specify dtype option on import or set low_memory=False.
  df = pd.read_csv(loader_path if human else f"{loader_path}{qid}.csv")
/var/folders/8s/b_t8p6s52r9c8k1j22zs0l740000gn/T/ipykernel_50204/940500852.py:11: DtypeWarning: Columns (19,21,22,23,25,26,27,29,30,35,37,38,1508,1509) have mixed types. Specify dtype option on import or set low_memory=False.
  df = pd.read_csv(loader_path if human else f"{loader_path}{qid}.csv")
/var/folders/8s/b_t8p6s52r9c8k1j22zs0l740000gn/T/ipykernel_50204/940500852.py:11: DtypeWarning: Columns (19,21,22,23,25,26,27,29,30,35,37,38,1508,1509) have mixed types. Specify dtype option on import or set low_memory=False.
  df = pd.read_csv(loader_path if human else f"{loader_path}{qid}.csv")
/var/folders/8s/b_t8p6s52r9c8k1j22zs0l740000gn/T/ipykernel_50204/940500852.py:11: DtypeWarning: Columns (19,21,22,23,25,26,27,29,30,35,37,38,1508,1509) have mixed types. Specify dtype option on import or set low_memory=False.
  df = pd.read_csv(loader_path if human else f"{loader_path}{qid}.csv")
/var/folders/8s/b_t8p6s52r9c8k1j22zs0l740000gn/T/ipykernel_50204/940500852.py:11: DtypeWarning: Columns (19,21,22,23,25,26,27,29,30,35,37,38,1508,1509) have mixed types. Specify dtype option on import or set low_memory=False.
  df = pd.read_csv(loader_path if human else f"{loader_path}{qid}.csv")
/var/folders/8s/b_t8p6s52r9c8k1j22zs0l740000gn/T/ipykernel_50204/940500852.py:11: DtypeWarning: Columns (19,21,22,23,25,26,27,29,30,35,37,38,1508,1509) have mixed types. Specify dtype option on import or set low_memory=False.
  df = pd.read_csv(loader_path if human else f"{loader_path}{qid}.csv")
/var/folders/8s/b_t8p6s52r9c8k1j22zs0l740000gn/T/ipykernel_50204/940500852.py:11: DtypeWarning: Columns (19,21,22,23,25,26,27,29,30,35,37,38,1508,1509) have mixed types. Specify dtype option on import or set low_memory=False.
  df = pd.read_csv(loader_path if human else f"{loader_path}{qid}.csv")
/var/folders/8s/b_t8p6s52r9c8k1j22zs0l740000gn/T/ipykernel_50204/940500852.py:11: DtypeWarning: Columns (19,21,22,23,25,26,27,29,30,35,37,38,1508,1509) have mixed types. Specify dtype option on import or set low_memory=False.
  df = pd.read_csv(loader_path if human else f"{loader_path}{qid}.csv")

Age loaded for: ['human', 'replicate', 'reformulated', 'priming', 'preamble']
variables now present: ['Race', 'Discuss Politics', 'Ideology', 'Party', 'Church', 'Gender', 'Political Interest', 'Age']

## Build the per-subgroup frames

The reverse-coded run is reloaded from disk in its raw (reverse-coded) state and un-reversed exactly
once, so its coding state is unambiguous. Age is included in that reload.

In [13]:
frames = {
    "reformulated": subgroup_gap_frame(results[1], results[2], results[0]),
    "priming":      subgroup_gap_frame(results[1], results[3], results[0]),
    "preamble":     subgroup_gap_frame(results[1], results[4], results[0]),
}

from copy import deepcopy

_UNREVERSE_SWAPS = {
    "Gay Marriage":      [(1, 3)],
    "Refugee Allowing":  [(1, 2)],
    "Income Inequality": [(1, 2)],
    "Gender Role":       [(1, 2)],
    "Climate Change":    [(1, 5), (2, 4)],
    "Race Diversity":    [(1, 2)],
}

def unreverse_counts(reversed_g):
    """Undo the reverse-coding. Does not mutate the input. Call once on the RAW data."""
    out = deepcopy(reversed_g)
    for group in out:
        for cat in out[group]:
            for entry in out[group][cat]:
                (item, counts), = entry.items()
                for a, b in _UNREVERSE_SWAPS.get(item, []):
                    counts[a], counts[b] = counts.get(b, 0), counts.get(a, 0)
    return out

_REV = f"{_MINI}/main_mq_reverseV2_results/full_results_2020_"
reversed_raw = {}
for key in groups_keys:
    reversed_raw[group_var_dict[key]] = get_counts_group(_REV, qids_reverse_coded, key)
reversed_raw["Age"] = _counts_age(_REV, qids_reverse_coded, human=False, labels=AGE_LABELS)

frames["reversed"] = subgroup_gap_frame(results[1], unreverse_counts(reversed_raw), results[0])

CONDITIONS = ["reformulated", "reversed", "priming", "preamble"]
GROUP_ORDER = ["Ideology", "Party", "Political Interest", "Church",
               "Gender", "Age", "Race", "Discuss Politics"]

long = []
for c in CONDITIONS:
    g = frames[c].copy()
    g.insert(0, "condition", c)
    long.append(g)
strat = pd.concat(long, ignore_index=True)

print(strat.shape)
print("variables:", sorted(strat['Group'].unique()))
print("items:", sorted(strat['item'].unique()))

(1155, 14)
variables: ['Age', 'Church', 'Discuss Politics', 'Gender', 'Ideology', 'Party', 'Political Interest', 'Race']
items: ['Climate Change', 'Drug Addiction', 'Gay Marriage', 'Gender Role', 'Gun Regulation', 'Health Insurance', 'Income Inequality', 'Race Diversity', 'Refugee Allowing']

## Results

In [14]:
ITEMS = ["Race Diversity", "Refugee Allowing", "Income Inequality"]

_sub = strat[strat["item"].isin(ITEMS)].copy()
_cols = pd.MultiIndex.from_product([CONDITIONS, ITEMS], names=["condition", "item"])
_gord = [g for g in GROUP_ORDER if g in set(_sub["Group"])]

def by_group(metric, nd=3):
    """Averaged over the subgroups within each variable."""
    return (_sub.pivot_table(index="Group", columns=["condition", "item"],
                             values=metric, aggfunc="mean")
            .reindex(index=_gord).reindex(columns=_cols).round(nd))

# D_base does not depend on the condition; take one block
def base_D(nd=3):
    b = (_sub[_sub["condition"] == CONDITIONS[0]]
         .pivot_table(index="Group", columns="item", values="D_base", aggfunc="mean"))
    return b.reindex(index=_gord)[ITEMS].round(nd)

print("Baseline signed desirability gap D at Replicate (mean over subgroups)")
display(base_D())

print("\ndelta JSD  (negative = improvement)")
display(by_group("delta_jsd"))

print("\ndelta |D|  (negative = improvement)")
display(by_group("delta_absD"))

Baseline signed desirability gap D at Replicate (mean over subgroups)

item                Race Diversity  Refugee Allowing  Income Inequality
Group
Ideology                     0.388             0.234              0.190
Party                        0.439             0.319              0.242
Political Interest           0.455             0.297              0.245
Church                       0.431             0.289              0.228
Gender                       0.430             0.286              0.220
Age                          0.427             0.279              0.217
Race                         0.416             0.322              0.214
Discuss Politics             0.508             0.398              0.325

delta JSD  (negative = improvement)

condition            reformulated                                     \
item               Race Diversity Refugee Allowing Income Inequality
Group
Ideology                   -0.060           -0.046             0.041
Party                      -0.074           -0.073             0.035
Political Interest         -0.085           -0.052             0.034
Church                     -0.077           -0.064             0.045
Gender                     -0.075           -0.061             0.047
Age                        -0.072           -0.059             0.050
Race                       -0.036           -0.069             0.069
Discuss Politics           -0.130           -0.122             0.036

condition                reversed                                     \
item               Race Diversity Refugee Allowing Income Inequality
Group
Ideology                   -0.139           -0.042             0.106
Party                      -0.146           -0.059             0.064
Political Interest         -0.151           -0.053            -0.040
Church                     -0.150           -0.045            -0.035
Gender                     -0.150           -0.045            -0.031
Age                        -0.149           -0.044            -0.030
Race                       -0.151           -0.057            -0.027
Discuss Politics           -0.193           -0.081            -0.061

condition                 priming                                     \
item               Race Diversity Refugee Allowing Income Inequality
Group
Ideology                    0.046            0.025             0.065
Party                       0.036            0.009             0.050
Political Interest          0.057            0.015             0.034
Church                      0.035            0.013             0.031
Gender                      0.037            0.013             0.035
Age                         0.037            0.014             0.033
Race                        0.037            0.028             0.028
Discuss Politics            0.042            0.005             0.032

condition                preamble
item               Race Diversity Refugee Allowing Income Inequality
Group
Ideology                   -0.017            0.133             0.065
Party                      -0.009            0.118             0.057
Political Interest          0.005            0.157             0.048
Church                     -0.013            0.133             0.035
Gender                     -0.013            0.134             0.038
Age                        -0.012            0.134             0.036
Race                       -0.001            0.145             0.021
Discuss Politics           -0.033            0.147             0.013

delta |D|  (negative = improvement)

condition            reformulated                                     \
item               Race Diversity Refugee Allowing Income Inequality
Group
Ideology                   -0.172           -0.122            -0.040
Party                      -0.147           -0.117            -0.016
Political Interest         -0.153           -0.169            -0.070
Church                     -0.159           -0.152            -0.044
Gender                     -0.159           -0.151            -0.041
Age                        -0.158           -0.153            -0.042
Race                       -0.124           -0.151            -0.043
Discuss Politics           -0.166           -0.212            -0.078

condition                reversed                                     \
item               Race Diversity Refugee Allowing Income Inequality
Group
Ideology                   -0.146           -0.086             0.145
Party                      -0.132           -0.109             0.078
Political Interest         -0.145           -0.124            -0.200
Church                     -0.137           -0.085            -0.146
Gender                     -0.140           -0.085            -0.165
Age                        -0.139           -0.086            -0.150
Race                       -0.142           -0.108            -0.190
Discuss Politics           -0.185           -0.111            -0.276

condition                 priming                                     \
item               Race Diversity Refugee Allowing Income Inequality
Group
Ideology                    0.023            0.027             0.092
Party                       0.013            0.026             0.078
Political Interest          0.024            0.032             0.068
Church                      0.013            0.033             0.072
Gender                      0.013            0.033             0.077
Age                         0.013            0.035             0.075
Race                        0.014            0.041             0.067
Discuss Politics            0.014            0.018             0.057

condition                preamble
item               Race Diversity Refugee Allowing Income Inequality
Group
Ideology                   -0.011            0.145             0.085
Party                      -0.005            0.125             0.080
Political Interest          0.005            0.156             0.080
Church                     -0.005            0.142             0.069
Gender                     -0.006            0.143             0.072
Age                        -0.006            0.144             0.073
Race                       -0.000            0.133             0.043
Discuss Politics           -0.018            0.124             0.024

### Per subgroup level (no averaging)

In [15]:
# substantive level ordering, taken from `groups` so it cannot drift
_CAT_ORDER = {group_var_dict[k]: list(v.values()) for k, v in groups.items()}
_CAT_ORDER["Age"] = list(AGE_LABELS.values())

MIN_N = 30      # mask a cell when the model or human subgroup has fewer responses

_lv = _sub.copy()
_thin = (_lv["n_model"] < MIN_N) | (_lv["n_human"] < MIN_N)
if _thin.any():
    print(f"masked {_thin.sum()} cells below MIN_N={MIN_N}:")
    for _, r in _lv[_thin].drop_duplicates(["Group", "Category", "item"]).iterrows():
        print(f"  {r['Group']}/{r['Category']}/{r['item']}: "
              f"n_model={int(r['n_model'])}, n_human={int(r['n_human'])}")
    _lv.loc[_thin, ["delta_jsd", "delta_absD", "D_base"]] = np.nan

_lidx = pd.MultiIndex.from_tuples(
    [(g, c) for g in _gord for c in _CAT_ORDER[g]], names=["Group", "Category"])

def by_level(metric, nd=3):
    return (_lv.pivot_table(index=["Group", "Category"], columns=["condition", "item"],
                            values=metric)
            .reindex(index=_lidx).reindex(columns=_cols).round(nd))

def base_D_level(nd=3):
    b = (_lv[_lv["condition"] == CONDITIONS[0]]
         .pivot_table(index=["Group", "Category"], columns="item", values="D_base"))
    return b.reindex(index=_lidx)[ITEMS].round(nd)

pd.set_option("display.max_rows", 200)

print("Baseline signed desirability gap D at Replicate, per level")
display(base_D_level())

print("\ndelta JSD per level")
display(by_level("delta_jsd"))

print("\ndelta |D| per level")
display(by_level("delta_absD"))

Baseline signed desirability gap D at Replicate, per level

item                                          Race Diversity  \
Group              Category
Ideology           Extremely liberal                   0.164
                   Liberal                             0.154
                   Slightly liberal                    0.223
                   Moderate                            0.445
                   Slightly conservative               0.524
                   Conservative                        0.627
                   Extremely conservative              0.577
Party              Strong democrat                     0.240
                   Weak democrat                       0.341
                   Democrat-leaning indep.             0.240
                   Independent                         0.542
                   Republican-leaning indep.           0.520
                   Weak republican                     0.550
                   Strong republican                   0.641
Political Interest Very                                0.334
                   Somewhat                            0.430
                   Not very                            0.480
                   Not at all                          0.575
Church             Attend church                       0.481
                   Does not attend church              0.381
Gender             Man                                 0.438
                   Woman                               0.423
Age                18-29                               0.424
                   30-39                               0.381
                   40-49                               0.425
                   50-59                               0.433
                   60-69                               0.424
                   70+                                 0.474
Race               White                               0.433
                   Black                               0.456
                   Asian                               0.422
                   Native American                     0.340
                   Hispanic                            0.430
Discuss Politics   Like to discuss politics            0.415
                   Never discuss politics              0.600

item                                          Refugee Allowing  \
Group              Category
Ideology           Extremely liberal                     0.089
                   Liberal                               0.110
                   Slightly liberal                      0.145
                   Moderate                              0.383
                   Slightly conservative                 0.456
                   Conservative                          0.304
                   Extremely conservative                0.151
Party              Strong democrat                       0.232
                   Weak democrat                         0.294
                   Democrat-leaning indep.               0.239
                   Independent                           0.476
                   Republican-leaning indep.             0.454
                   Weak republican                       0.416
                   Strong republican                     0.120
Political Interest Very                                  0.204
                   Somewhat                              0.278
                   Not very                              0.368
                   Not at all                            0.338
Church             Attend church                         0.347
                   Does not attend church                0.232
Gender             Man                                   0.288
                   Woman                                 0.284
Age                18-29                                 0.211
                   30-39                                 0.255
                   40-49                                 0.295
                   50-59                                 0.321
                   60-69                                 0.304
                   70+                                   0.291
Race               White                                 0.274
                   Black                                 0.342
                   Asian                                 0.299
                   Native American                       0.290
                   Hispanic                              0.404
Discuss Politics   Like to discuss politics              0.264
                   Never discuss politics                0.531

item                                          Income Inequality
Group              Category
Ideology           Extremely liberal                      0.083
                   Liberal                                0.075
                   Slightly liberal                       0.125
                   Moderate                               0.279
                   Slightly conservative                  0.382
                   Conservative                           0.230
                   Extremely conservative                 0.154
Party              Strong democrat                        0.234
                   Weak democrat                          0.198
                   Democrat-leaning indep.                0.243
                   Independent                            0.330
                   Republican-leaning indep.              0.280
                   Weak republican                        0.401
                   Strong republican                      0.008
Political Interest Very                                   0.144
                   Somewhat                               0.220
                   Not very                               0.306
                   Not at all                             0.312
Church             Attend church                          0.317
                   Does not attend church                 0.139
Gender             Man                                    0.194
                   Woman                                  0.247
Age                18-29                                  0.129
                   30-39                                  0.151
                   40-49                                  0.246
                   50-59                                  0.240
                   60-69                                  0.236
                   70+                                    0.299
Race               White                                  0.230
                   Black                                  0.194
                   Asian                                  0.232
                   Native American                        0.126
                   Hispanic                               0.289
Discuss Politics   Like to discuss politics               0.205
                   Never discuss politics                 0.444

delta JSD per level

condition                                      reformulated                   \
item                                         Race Diversity Refugee Allowing
Group              Category
Ideology           Extremely liberal                 -0.021           -0.011
                   Liberal                           -0.016           -0.029
                   Slightly liberal                  -0.046           -0.010
                   Moderate                          -0.064           -0.096
                   Slightly conservative             -0.125           -0.103
                   Conservative                      -0.154           -0.063
                   Extremely conservative             0.004           -0.010
Party              Strong democrat                   -0.004           -0.038
                   Weak democrat                     -0.034           -0.043
                   Democrat-leaning indep.            0.000           -0.052
                   Independent                       -0.142           -0.159
                   Republican-leaning indep.         -0.096           -0.152
                   Weak republican                   -0.129           -0.099
                   Strong republican                 -0.115            0.029
Political Interest Very                              -0.043           -0.021
                   Somewhat                          -0.067           -0.040
                   Not very                          -0.082           -0.100
                   Not at all                        -0.146           -0.047
Church             Attend church                     -0.102           -0.078
                   Does not attend church            -0.052           -0.049
Gender             Man                               -0.089           -0.057
                   Woman                             -0.061           -0.066
Age                18-29                             -0.072           -0.048
                   30-39                             -0.034           -0.055
                   40-49                             -0.068           -0.062
                   50-59                             -0.083           -0.062
                   60-69                             -0.091           -0.073
                   70+                               -0.086           -0.055
Race               White                             -0.082           -0.060
                   Black                             -0.083           -0.053
                   Asian                             -0.007           -0.072
                   Native American                   -0.005           -0.053
                   Hispanic                          -0.006           -0.105
Discuss Politics   Like to discuss politics          -0.059           -0.053
                   Never discuss politics            -0.201           -0.190

condition                                                            reversed  \
item                                         Income Inequality Race Diversity
Group              Category
Ideology           Extremely liberal                     0.037         -0.019
                   Liberal                               0.049         -0.021
                   Slightly liberal                      0.064         -0.072
                   Moderate                              0.027         -0.171
                   Slightly conservative                 0.001         -0.185
                   Conservative                          0.051         -0.278
                   Extremely conservative                0.057         -0.230
Party              Strong democrat                       0.031         -0.059
                   Weak democrat                         0.042         -0.090
                   Democrat-leaning indep.               0.031         -0.070
                   Independent                           0.046         -0.152
                   Republican-leaning indep.            -0.054         -0.186
                   Weak republican                       0.002         -0.175
                   Strong republican                     0.145         -0.293
Political Interest Very                                  0.045         -0.112
                   Somewhat                              0.058         -0.150
                   Not very                              0.022         -0.168
                   Not at all                            0.011         -0.173
Church             Attend church                         0.023         -0.167
                   Does not attend church                0.067         -0.133
Gender             Man                                   0.043         -0.171
                   Woman                                 0.052         -0.128
Age                18-29                                 0.092         -0.149
                   30-39                                 0.068         -0.146
                   40-49                                 0.048         -0.168
                   50-59                                 0.044         -0.142
                   60-69                                 0.028         -0.142
                   70+                                   0.017         -0.149
Race               White                                 0.043         -0.147
                   Black                                 0.080         -0.183
                   Asian                                 0.048         -0.142
                   Native American                       0.092         -0.123
                   Hispanic                              0.080         -0.160
Discuss Politics   Like to discuss politics              0.045         -0.142
                   Never discuss politics                0.026         -0.243

condition                                                      \
item                                         Refugee Allowing
Group              Category
Ideology           Extremely liberal                   -0.018
                   Liberal                              0.002
                   Slightly liberal                    -0.003
                   Moderate                            -0.096
                   Slightly conservative               -0.135
                   Conservative                        -0.026
                   Extremely conservative              -0.020
Party              Strong democrat                     -0.038
                   Weak democrat                       -0.060
                   Democrat-leaning indep.             -0.061
                   Independent                         -0.159
                   Republican-leaning indep.           -0.097
                   Weak republican                     -0.077
                   Strong republican                    0.076
Political Interest Very                                -0.012
                   Somewhat                            -0.044
                   Not very                            -0.084
                   Not at all                          -0.074
Church             Attend church                       -0.053
                   Does not attend church              -0.036
Gender             Man                                 -0.048
                   Woman                               -0.042
Age                18-29                               -0.041
                   30-39                               -0.042
                   40-49                               -0.050
                   50-59                               -0.032
                   60-69                               -0.058
                   70+                                 -0.038
Race               White                               -0.038
                   Black                               -0.068
                   Asian                               -0.080
                   Native American                     -0.048
                   Hispanic                            -0.051
Discuss Politics   Like to discuss politics            -0.043
                   Never discuss politics              -0.120

condition                                                             priming  \
item                                         Income Inequality Race Diversity
Group              Category
Ideology           Extremely liberal                     0.153          0.000
                   Liberal                               0.128          0.008
                   Slightly liberal                      0.062          0.000
                   Moderate                             -0.044          0.016
                   Slightly conservative                -0.040          0.008
                   Conservative                          0.169          0.063
                   Extremely conservative                0.315          0.226
Party              Strong democrat                       0.051          0.006
                   Weak democrat                         0.017          0.016
                   Democrat-leaning indep.               0.071          0.000
                   Independent                          -0.081          0.027
                   Republican-leaning indep.             0.065          0.047
                   Weak republican                      -0.095          0.057
                   Strong republican                     0.421          0.099
Political Interest Very                                 -0.017          0.007
                   Somewhat                             -0.028          0.029
                   Not very                             -0.061          0.067
                   Not at all                           -0.054          0.125
Church             Attend church                        -0.062          0.016
                   Does not attend church               -0.007          0.054
Gender             Man                                  -0.024          0.032
                   Woman                                -0.037          0.043
Age                18-29                                 0.004          0.023
                   30-39                                -0.009          0.036
                   40-49                                -0.042          0.028
                   50-59                                -0.036          0.042
                   60-69                                -0.040          0.049
                   70+                                  -0.057          0.043
Race               White                                -0.034          0.042
                   Black                                -0.018          0.000
                   Asian                                -0.027          0.053
                   Native American                       0.001          0.039
                   Hispanic                             -0.059          0.051
Discuss Politics   Like to discuss politics             -0.027          0.033
                   Never discuss politics               -0.094          0.050

condition                                                      \
item                                         Refugee Allowing
Group              Category
Ideology           Extremely liberal                    0.008
                   Liberal                              0.017
                   Slightly liberal                     0.032
                   Moderate                             0.032
                   Slightly conservative                0.050
                   Conservative                         0.057
                   Extremely conservative              -0.022
Party              Strong democrat                     -0.004
                   Weak democrat                        0.016
                   Democrat-leaning indep.             -0.010
                   Independent                         -0.014
                   Republican-leaning indep.            0.029
                   Weak republican                      0.025
                   Strong republican                    0.021
Political Interest Very                                -0.008
                   Somewhat                             0.021
                   Not very                             0.035
                   Not at all                           0.013
Church             Attend church                        0.020
                   Does not attend church               0.005
Gender             Man                                  0.011
                   Woman                                0.014
Age                18-29                                0.005
                   30-39                                0.003
                   40-49                                0.011
                   50-59                                0.050
                   60-69                               -0.002
                   70+                                  0.018
Race               White                                0.009
                   Black                                0.033
                   Asian                                0.019
                   Native American                      0.013
                   Hispanic                             0.064
Discuss Politics   Like to discuss politics             0.020
                   Never discuss politics              -0.009

condition                                                            preamble  \
item                                         Income Inequality Race Diversity
Group              Category
Ideology           Extremely liberal                     0.047          0.000
                   Liberal                               0.056          0.003
                   Slightly liberal                      0.082         -0.010
                   Moderate                              0.061         -0.002
                   Slightly conservative                 0.103         -0.012
                   Conservative                          0.078         -0.040
                   Extremely conservative                0.026         -0.055
Party              Strong democrat                       0.013          0.006
                   Weak democrat                         0.046         -0.004
                   Democrat-leaning indep.               0.018          0.000
                   Independent                           0.024         -0.005
                   Republican-leaning indep.             0.150         -0.017
                   Weak republican                       0.046         -0.018
                   Strong republican                     0.052         -0.025
Political Interest Very                                  0.036         -0.018
                   Somewhat                              0.035         -0.034
                   Not very                              0.032          0.021
                   Not at all                            0.031          0.049
Church             Attend church                         0.040         -0.026
                   Does not attend church                0.023         -0.001
Gender             Man                                   0.044         -0.031
                   Woman                                 0.025          0.005
Age                18-29                                 0.018         -0.004
                   30-39                                 0.028          0.002
                   40-49                                 0.031         -0.023
                   50-59                                 0.034         -0.004
                   60-69                                 0.058         -0.005
                   70+                                   0.032         -0.037
Race               White                                 0.040         -0.014
                   Black                                 0.009         -0.008
                   Asian                                 0.027          0.005
                   Native American                       0.013          0.011
                   Hispanic                              0.053          0.004
Discuss Politics   Like to discuss politics              0.040         -0.007
                   Never discuss politics                0.024         -0.059

condition                                                      \
item                                         Refugee Allowing
Group              Category
Ideology           Extremely liberal                    0.031
                   Liberal                              0.037
                   Slightly liberal                     0.097
                   Moderate                             0.156
                   Slightly conservative                0.197
                   Conservative                         0.259
                   Extremely conservative               0.153
Party              Strong democrat                      0.015
                   Weak democrat                        0.084
                   Democrat-leaning indep.              0.014
                   Independent                          0.114
                   Republican-leaning indep.            0.147
                   Weak republican                      0.184
                   Strong republican                    0.270
Political Interest Very                                 0.077
                   Somewhat                             0.129
                   Not very                             0.203
                   Not at all                           0.218
Church             Attend church                        0.146
                   Does not attend church               0.119
Gender             Man                                  0.130
                   Woman                                0.137
Age                18-29                                0.105
                   30-39                                0.112
                   40-49                                0.155
                   50-59                                0.161
                   60-69                                0.122
                   70+                                  0.151
Race               White                                0.132
                   Black                                0.177
                   Asian                                0.109
                   Native American                      0.154
                   Hispanic                             0.151
Discuss Politics   Like to discuss politics             0.134
                   Never discuss politics               0.161

condition
item                                         Income Inequality
Group              Category
Ideology           Extremely liberal                     0.051
                   Liberal                               0.042
                   Slightly liberal                      0.043
                   Moderate                              0.072
                   Slightly conservative                 0.098
                   Conservative                          0.096
                   Extremely conservative                0.054
Party              Strong democrat                       0.020
                   Weak democrat                         0.040
                   Democrat-leaning indep.               0.040
                   Independent                           0.046
                   Republican-leaning indep.             0.107
                   Weak republican                       0.089
                   Strong republican                     0.060
Political Interest Very                                  0.038
                   Somewhat                              0.035
                   Not very                              0.054
                   Not at all                            0.064
Church             Attend church                         0.047
                   Does not attend church                0.024

delta |D| per level

condition                                      reformulated                   \
item                                         Race Diversity Refugee Allowing
Group              Category
Ideology           Extremely liberal                 -0.065           -0.074
                   Liberal                           -0.019           -0.077
                   Slightly liberal                  -0.059           -0.104
                   Moderate                          -0.034           -0.182
                   Slightly conservative             -0.240           -0.171
                   Conservative                      -0.393           -0.178
                   Extremely conservative            -0.392           -0.064
Party              Strong democrat                   -0.002           -0.028
                   Weak democrat                     -0.017           -0.067
                   Democrat-leaning indep.            0.000           -0.041
                   Independent                       -0.109           -0.235
                   Republican-leaning indep.         -0.206           -0.302
                   Weak republican                   -0.222           -0.175
                   Strong republican                 -0.476            0.031
Political Interest Very                              -0.175           -0.102
                   Somewhat                          -0.157           -0.095
                   Not very                          -0.124           -0.238
                   Not at all                        -0.158           -0.243
Church             Attend church                     -0.175           -0.160
                   Does not attend church            -0.143           -0.144
Gender             Man                               -0.161           -0.134
                   Woman                             -0.157           -0.167
Age                18-29                             -0.114           -0.190
                   30-39                             -0.130           -0.151
                   40-49                             -0.161           -0.172
                   50-59                             -0.177           -0.130
                   60-69                             -0.189           -0.157
                   70+                               -0.175           -0.120
Race               White                             -0.173           -0.154
                   Black                             -0.131           -0.118
                   Asian                             -0.107           -0.166
                   Native American                   -0.134           -0.124
                   Hispanic                          -0.075           -0.195
Discuss Politics   Like to discuss politics          -0.152           -0.138
                   Never discuss politics            -0.180           -0.287

condition                                                            reversed  \
item                                         Income Inequality Race Diversity
Group              Category
Ideology           Extremely liberal                    -0.031         -0.008
                   Liberal                              -0.049         -0.013
                   Slightly liberal                     -0.068         -0.050
                   Moderate                             -0.013         -0.145
                   Slightly conservative                -0.152         -0.128
                   Conservative                         -0.014         -0.276
                   Extremely conservative                0.047         -0.404
Party              Strong democrat                       0.021         -0.041
                   Weak democrat                        -0.016         -0.068
                   Democrat-leaning indep.               0.025         -0.047
                   Independent                          -0.038         -0.103
                   Republican-leaning indep.            -0.111         -0.188
                   Weak republican                      -0.060         -0.156
                   Strong republican                     0.070         -0.320
Political Interest Very                                 -0.016         -0.083
                   Somewhat                             -0.037         -0.129
                   Not very                             -0.095         -0.192
                   Not at all                           -0.133         -0.173
Church             Attend church                        -0.055         -0.125
                   Does not attend church               -0.033         -0.149
Gender             Man                                  -0.021         -0.170
                   Woman                                -0.060         -0.109
Age                18-29                                -0.020         -0.128
                   30-39                                 0.013         -0.150
                   40-49                                -0.052         -0.164
                   50-59                                -0.068         -0.128
                   60-69                                -0.043         -0.140
                   70+                                  -0.083         -0.125
Race               White                                -0.044         -0.137
                   Black                                -0.044         -0.135
                   Asian                                -0.047         -0.140
                   Native American                      -0.056         -0.134
                   Hispanic                             -0.024         -0.162
Discuss Politics   Like to discuss politics             -0.042         -0.126
                   Never discuss politics               -0.114         -0.244

condition                                                      \
item                                         Refugee Allowing
Group              Category
Ideology           Extremely liberal                   -0.027
                   Liberal                             -0.039
                   Slightly liberal                    -0.081
                   Moderate                            -0.155
                   Slightly conservative               -0.212
                   Conservative                        -0.041
                   Extremely conservative              -0.049
Party              Strong democrat                     -0.026
                   Weak democrat                       -0.116
                   Democrat-leaning indep.             -0.054
                   Independent                         -0.246
                   Republican-leaning indep.           -0.196
                   Weak republican                     -0.161
                   Strong republican                    0.038
Political Interest Very                                -0.024
                   Somewhat                            -0.089
                   Not very                            -0.166
                   Not at all                          -0.218
Church             Attend church                       -0.076
                   Does not attend church              -0.094
Gender             Man                                 -0.090
                   Woman                               -0.080
Age                18-29                               -0.107
                   30-39                               -0.083
                   40-49                               -0.107
                   50-59                               -0.044
                   60-69                               -0.105
                   70+                                 -0.071
Race               White                               -0.069
                   Black                               -0.136
                   Asian                               -0.165
                   Native American                     -0.100
                   Hispanic                            -0.072
Discuss Politics   Like to discuss politics            -0.082
                   Never discuss politics              -0.139

condition                                                             priming  \
item                                         Income Inequality Race Diversity
Group              Category
Ideology           Extremely liberal                     0.208          0.000
                   Liberal                               0.175          0.003
                   Slightly liberal                      0.048          0.000
                   Moderate                             -0.122          0.004
                   Slightly conservative                -0.085          0.002
                   Conservative                          0.305          0.023
                   Extremely conservative                0.486          0.128
Party              Strong democrat                       0.047          0.002
                   Weak democrat                         0.077          0.005
                   Democrat-leaning indep.               0.141          0.000
                   Independent                          -0.309          0.008
                   Republican-leaning indep.             0.081          0.017
                   Weak republican                      -0.205          0.020
                   Strong republican                     0.714          0.040
Political Interest Very                                 -0.125          0.002
                   Somewhat                             -0.123          0.009
                   Not very                             -0.289          0.029
                   Not at all                           -0.264          0.058
Church             Attend church                        -0.178          0.004
                   Does not attend church               -0.115          0.023
Gender             Man                                  -0.124          0.011
                   Woman                                -0.205          0.015
Age                18-29                                -0.066          0.007
                   30-39                                -0.148          0.013
                   40-49                                -0.185          0.009
                   50-59                                -0.146          0.016
                   60-69                                -0.168          0.020
                   70+                                  -0.186          0.014
Race               White                                -0.151          0.015
                   Black                                -0.180          0.000
                   Asian                                -0.216          0.020
                   Native American                      -0.123          0.015
                   Hispanic                             -0.280          0.019
Discuss Politics   Like to discuss politics             -0.144          0.011
                   Never discuss politics               -0.408          0.017

condition                                                      \
item                                         Refugee Allowing
Group              Category
Ideology           Extremely liberal                    0.011
                   Liberal                              0.014
                   Slightly liberal                     0.054
                   Moderate                             0.024
                   Slightly conservative                0.044
                   Conservative                         0.082
                   Extremely conservative              -0.042
Party              Strong democrat                     -0.002
                   Weak democrat                        0.016
                   Democrat-leaning indep.             -0.005
                   Independent                         -0.018
                   Republican-leaning indep.            0.021
                   Weak republican                      0.032
                   Strong republican                    0.138
Political Interest Very                                 0.021
                   Somewhat                             0.049
                   Not very                             0.042
                   Not at all                           0.017
Church             Attend church                        0.035
                   Does not attend church               0.031
Gender             Man                                  0.033
                   Woman                                0.033
Age                18-29                                0.020
                   30-39                                0.022
                   40-49                                0.029
                   50-59                                0.072
                   60-69                                0.015
                   70+                                  0.055
Race               White                                0.032
                   Black                                0.040
                   Asian                                0.041
                   Native American                      0.027
                   Hispanic                             0.064
Discuss Politics   Like to discuss politics             0.048
                   Never discuss politics              -0.011

condition                                                            preamble  \
item                                         Income Inequality Race Diversity
Group              Category
Ideology           Extremely liberal                     0.057          0.000
                   Liberal                               0.089          0.001
                   Slightly liberal                      0.143         -0.003
                   Moderate                              0.088         -0.001
                   Slightly conservative                 0.134         -0.004
                   Conservative                          0.091         -0.020
                   Extremely conservative                0.043         -0.052
Party              Strong democrat                       0.011          0.002
                   Weak democrat                         0.065         -0.001
                   Democrat-leaning indep.               0.015          0.000
                   Independent                           0.028         -0.002
                   Republican-leaning indep.             0.152         -0.008
                   Weak republican                       0.046         -0.009
                   Strong republican                     0.231         -0.014
Political Interest Very                                  0.096         -0.007
                   Somewhat                              0.081         -0.016
                   Not very                              0.053          0.011
                   Not at all                            0.041          0.029
Church             Attend church                         0.065         -0.010
                   Does not attend church                0.079         -0.000
Gender             Man                                   0.101         -0.015
                   Woman                                 0.052          0.002
Age                18-29                                 0.072         -0.001
                   30-39                                 0.084          0.001
                   40-49                                 0.064         -0.010
                   50-59                                 0.066         -0.001
                   60-69                                 0.113         -0.003
                   70+                                   0.050         -0.019
Race               White                                 0.083         -0.007
                   Black                                 0.026         -0.002
                   Asian                                 0.065          0.002
                   Native American                       0.065          0.004
                   Hispanic                              0.096          0.002
Discuss Politics   Like to discuss politics              0.093         -0.003
                   Never discuss politics                0.020         -0.033

condition                                                      \
item                                         Refugee Allowing
Group              Category
Ideology           Extremely liberal                    0.023
                   Liberal                              0.023
                   Slightly liberal                     0.098
                   Moderate                             0.101
                   Slightly conservative                0.130
                   Conservative                         0.304
                   Extremely conservative               0.339
Party              Strong democrat                      0.005
                   Weak democrat                        0.053
                   Democrat-leaning indep.              0.005
                   Independent                          0.068
                   Republican-leaning indep.            0.106
                   Weak republican                      0.152
                   Strong republican                    0.486
Political Interest Very                                 0.117
                   Somewhat                             0.148
                   Not very                             0.156
                   Not at all                           0.202
Church             Attend church                        0.134
                   Does not attend church               0.150
Gender             Man                                  0.150
                   Woman                                0.137
Age                18-29                                0.118
                   30-39                                0.120
                   40-49                                0.155
                   50-59                                0.169
                   60-69                                0.127
                   70+                                  0.175
Race               White                                0.149
                   Black                                0.154
                   Asian                                0.112
                   Native American                      0.132
                   Hispanic                             0.118
Discuss Politics   Like to discuss politics             0.150
                   Never discuss politics               0.098

condition
item                                         Income Inequality
Group              Category
Ideology           Extremely liberal                     0.058
                   Liberal                               0.076
                   Slightly liberal                      0.086
                   Moderate                              0.085
                   Slightly conservative                 0.098
                   Conservative                          0.086
                   Extremely conservative                0.106
Party              Strong democrat                       0.014
                   Weak democrat                         0.066
                   Democrat-leaning indep.               0.030
                   Independent                           0.057
                   Republican-leaning indep.             0.102
                   Weak republican                       0.097
                   Strong republican                     0.192
Political Interest Very                                  0.078
                   Somewhat                              0.059
                   Not very                              0.072
                   Not at all                            0.111
Church             Attend church                         0.067
                   Does not attend church                0.071

### Save

In [ ]:
import os
outdir = "../tables-stochastic/stratified"
os.makedirs(outdir, exist_ok=True)

cols = ["condition", "Group", "Category", "item", "D_base", "D_cond",
        "delta_jsd", "delta_absD", "jsd_base", "jsd_cond", "n_model", "n_human"]
strat[cols].round(4).to_csv(f"{outdir}/{model_name}_stratified_long.csv", index=False)

for name, tbl in [("baseD_group", base_D()), ("deltaJSD_group", by_group("delta_jsd")),
                  ("deltaabsD_group", by_group("delta_absD")),
                  ("baseD_level", base_D_level()), ("deltaJSD_level", by_level("delta_jsd")),
                  ("deltaabsD_level", by_level("delta_absD"))]:
    tbl.to_csv(f"{outdir}/{model_name}_{name}.csv")

print("saved to", outdir)

## Full results: all items, all four conditions

In [ ]:
ALL_ITEMS = [name_dict[q] for q in qids if name_dict[q] in set(strat["item"])]
_dropped  = [name_dict[q] for q in qids if name_dict[q] not in set(strat["item"])]
print(f"{len(ALL_ITEMS)} directional items:", ALL_ITEMS)
if _dropped:
    print("absent (non-directional, no desirability gap):", _dropped)

# coverage per condition: the reverse-coded run carries only its own subset
_cov = (strat.groupby("condition")["item"].nunique().reindex(CONDITIONS))
print("\nitems present per condition:")
for c, n in _cov.items():
    miss = sorted(set(ALL_ITEMS) - set(strat.loc[strat.condition == c, "item"]))
    print(f"  {c:14s} {n}" + (f"   missing: {miss}" if miss else ""))

COMMON_ITEMS = sorted(set.intersection(*(set(strat.loc[strat.condition == c, "item"])
                                         for c in CONDITIONS)), key=ALL_ITEMS.index)
print("\nitems common to all four conditions:", COMMON_ITEMS)
print("NOTE: the Average column below spans whatever items a condition has, so the reverse-coded")
print("      average covers fewer items. Pass items=COMMON_ITEMS for a comparable average.")

MIN_N_FULL = 30            # mask a subgroup cell below this many responses

_full = strat.copy()
_thin = (_full["n_model"] < MIN_N_FULL) | (_full["n_human"] < MIN_N_FULL)
if _thin.any():
    print(f"\nmasked {_thin.sum()} thin cells (< {MIN_N_FULL} responses):")
    for _, r in (_full[_thin].drop_duplicates(["Group", "Category"])
                 .sort_values(["Group", "Category"]).iterrows()):
        print(f"  {r['Group']}/{r['Category']}: n_model={int(r['n_model'])}, "
              f"n_human={int(r['n_human'])}")
    _full.loc[_thin, ["delta_jsd", "delta_absD", "D_base"]] = np.nan

_gord_full = [g for g in GROUP_ORDER if g in set(_full["Group"])]
_lidx_full = pd.MultiIndex.from_tuples(
    [(g, c) for g in _gord_full for c in _CAT_ORDER[g]], names=["Group", "Category"])


def full_group(metric, condition, items=None, nd=3, average=True):
    """Subgroup-averaged metric for one condition: variables down, items across."""
    items = items or ALL_ITEMS
    t = (_full[_full["condition"] == condition]
         .pivot_table(index="Group", columns="item", values=metric, aggfunc="mean")
         .reindex(index=_gord_full).reindex(columns=items))
    if average:
        t["Average"] = t.mean(axis=1)
    return t.round(nd)


def full_level(metric, condition, items=None, nd=3, average=True):
    """Same, without averaging over subgroups: every level down, items across."""
    items = items or ALL_ITEMS
    t = (_full[_full["condition"] == condition]
         .pivot_table(index=["Group", "Category"], columns="item", values=metric)
         .reindex(index=_lidx_full).reindex(columns=items))
    if average:
        t["Average"] = t.mean(axis=1)
    return t.round(nd)


def full_baseD(level=False, items=None, nd=3):
    """Baseline signed gap D at Replicate. Identical across conditions, so read one block."""
    items = items or ALL_ITEMS
    idx = ["Group", "Category"] if level else "Group"
    t = (_full[_full["condition"] == CONDITIONS[0]]
         .pivot_table(index=idx, columns="item", values="D_base"))
    return t.reindex(index=_lidx_full if level else _gord_full).reindex(columns=items).round(nd)

9 directional items: ['Gay Marriage', 'Refugee Allowing', 'Income Inequality', 'Gender Role', 'Climate Change', 'Gun Regulation', 'Drug Addiction', 'Race Diversity', 'Health Insurance']
absent (non-directional, no desirability gap): ['Current Economy']

items present per condition:
  reformulated   9
  reversed       6   missing: ['Drug Addiction', 'Gun Regulation', 'Health Insurance']
  priming        9
  preamble       9

items common to all four conditions: ['Gay Marriage', 'Refugee Allowing', 'Income Inequality', 'Gender Role', 'Climate Change', 'Race Diversity']
NOTE: the Average column below spans whatever items a condition has, so the reverse-coded
      average covers fewer items. Pass items=COMMON_ITEMS for a comparable average.

In [ ]:
# Group level (averaged within each demographic variable)
pd.set_option("display.max_columns", 40)
pd.set_option("display.width", 250)

print("Baseline signed desirability gap D at Replicate\n")
display(full_baseD())

for metric, title in [("delta_jsd", "delta JSD"), ("delta_absD", "delta |D|")]:
    for c in CONDITIONS:
        print(f"\n{title}  |  {c}   (negative = improvement)")
        display(full_group(metric, c))

Baseline signed desirability gap D at Replicate

item                Gay Marriage  Refugee Allowing  Income Inequality  Gender Role  Climate Change  Gun Regulation  Drug Addiction  Race Diversity  Health Insurance
Group
Ideology                   0.135             0.234              0.190       -0.041           0.098           0.040           0.282           0.388             0.189
Party                      0.156             0.319              0.242       -0.048           0.100           0.052           0.316           0.439             0.221
Political Interest         0.147             0.297              0.245       -0.051           0.097           0.057           0.311           0.455             0.213
Church                     0.155             0.289              0.228       -0.047           0.096           0.050           0.302           0.431             0.201
Gender                     0.150             0.286              0.220       -0.048           0.095           0.051           0.301           0.430             0.197
Age                        0.145             0.279              0.217       -0.051           0.092           0.047           0.302           0.427             0.190
Race                       0.164             0.322              0.214       -0.071           0.080           0.041           0.292           0.416             0.203
Discuss Politics           0.179             0.398              0.325       -0.055           0.126           0.088           0.324           0.508             0.265

delta JSD  |  reformulated   (negative = improvement)

item                Gay Marriage  Refugee Allowing  Income Inequality  Gender Role  Climate Change  Gun Regulation  Drug Addiction  Race Diversity  Health Insurance  Average
Group
Ideology                  -0.004            -0.046              0.041       -0.013          -0.040           0.037          -0.013          -0.060             0.034   -0.007
Party                      0.003            -0.073              0.035       -0.059          -0.032           0.025          -0.013          -0.074             0.025   -0.018
Political Interest        -0.007            -0.052              0.034       -0.065          -0.022           0.009          -0.025          -0.085             0.019   -0.021
Church                    -0.006            -0.064              0.045       -0.060          -0.032           0.013          -0.024          -0.077             0.023   -0.020
Gender                    -0.006            -0.061              0.047       -0.059          -0.034           0.013          -0.023          -0.075             0.023   -0.019
Age                       -0.008            -0.059              0.050       -0.058          -0.031           0.012          -0.023          -0.072             0.023   -0.019
Race                      -0.008            -0.069              0.069       -0.070          -0.022           0.009          -0.023          -0.036             0.013   -0.015
Discuss Politics          -0.019            -0.122              0.036       -0.084          -0.040          -0.001          -0.023          -0.130             0.006   -0.042

delta JSD  |  reversed   (negative = improvement)

item                Gay Marriage  Refugee Allowing  Income Inequality  Gender Role  Climate Change  Gun Regulation  Drug Addiction  Race Diversity  Health Insurance  Average
Group
Ideology                   0.055            -0.042              0.106        0.765           0.258             NaN             NaN          -0.139               NaN    0.167
Party                      0.048            -0.059              0.064        0.750           0.312             NaN             NaN          -0.146               NaN    0.161
Political Interest         0.050            -0.053             -0.040        0.760           0.301             NaN             NaN          -0.151               NaN    0.145
Church                     0.063            -0.045             -0.035        0.777           0.271             NaN             NaN          -0.150               NaN    0.147
Gender                     0.060            -0.045             -0.031        0.775           0.269             NaN             NaN          -0.150               NaN    0.146
Age                        0.058            -0.044             -0.030        0.774           0.268             NaN             NaN          -0.149               NaN    0.146
Race                       0.064            -0.057             -0.027        0.714           0.281             NaN             NaN          -0.151               NaN    0.137
Discuss Politics           0.055            -0.081             -0.061        0.745           0.319             NaN             NaN          -0.193               NaN    0.131

delta JSD  |  priming   (negative = improvement)

item                Gay Marriage  Refugee Allowing  Income Inequality  Gender Role  Climate Change  Gun Regulation  Drug Addiction  Race Diversity  Health Insurance  Average
Group
Ideology                  -0.015             0.025              0.065        0.106           0.188           0.004           0.010           0.046             0.049    0.053
Party                     -0.002             0.009              0.050        0.088           0.182          -0.001           0.006           0.036             0.040    0.045
Political Interest        -0.010             0.015              0.034        0.111           0.166           0.011           0.006           0.057             0.029    0.046
Church                    -0.014             0.013              0.031        0.113           0.147           0.006           0.009           0.035             0.031    0.041
Gender                    -0.013             0.013              0.035        0.112           0.146           0.006           0.010           0.037             0.032    0.042
Age                       -0.012             0.014              0.033        0.111           0.144           0.005           0.010           0.037             0.031    0.041
Race                       0.002             0.028              0.028        0.101           0.135           0.003           0.007           0.037             0.015    0.040
Discuss Politics          -0.007             0.005              0.032        0.091           0.179           0.006           0.010           0.042             0.017    0.042

delta JSD  |  preamble   (negative = improvement)

item                Gay Marriage  Refugee Allowing  Income Inequality  Gender Role  Climate Change  Gun Regulation  Drug Addiction  Race Diversity  Health Insurance  Average
Group
Ideology                   0.009             0.133              0.065        0.036           0.038           0.013           0.010          -0.017             0.145    0.048
Party                      0.017             0.118              0.057        0.032           0.031           0.005           0.006          -0.009             0.136    0.044
Political Interest         0.016             0.157              0.048        0.050           0.025           0.017           0.006           0.005             0.150    0.053
Church                     0.011             0.133              0.035        0.045           0.022           0.008           0.009          -0.013             0.121    0.041
Gender                     0.011             0.134              0.038        0.045           0.021           0.010           0.010          -0.013             0.124    0.042
Age                        0.009             0.134              0.036        0.046           0.022           0.007           0.010          -0.012             0.123    0.042
Race                       0.011             0.145              0.021        0.036           0.016           0.008           0.007          -0.001             0.108    0.039
Discuss Politics           0.013             0.147              0.013        0.022           0.030           0.006           0.010          -0.033             0.119    0.037

delta |D|  |  reformulated   (negative = improvement)

item                Gay Marriage  Refugee Allowing  Income Inequality  Gender Role  Climate Change  Gun Regulation  Drug Addiction  Race Diversity  Health Insurance  Average
Group
Ideology                   0.003            -0.122             -0.040        0.101          -0.043           0.030          -0.074          -0.172             0.044   -0.030
Party                     -0.004            -0.117             -0.016        0.001          -0.047           0.013          -0.050          -0.147             0.039   -0.036
Political Interest        -0.017            -0.169             -0.070       -0.004          -0.040          -0.036          -0.051          -0.153             0.034   -0.056
Church                    -0.015            -0.152             -0.044        0.009          -0.046          -0.004          -0.062          -0.159             0.036   -0.048
Gender                    -0.013            -0.151             -0.041        0.005          -0.045          -0.026          -0.062          -0.159             0.034   -0.051
Age                       -0.019            -0.153             -0.042        0.006          -0.039          -0.022          -0.061          -0.158             0.037   -0.050
Race                      -0.034            -0.151             -0.043       -0.041          -0.010          -0.016          -0.055          -0.124             0.025   -0.050
Discuss Politics          -0.041            -0.212             -0.078       -0.023          -0.088          -0.062          -0.054          -0.166             0.012   -0.079

delta |D|  |  reversed   (negative = improvement)

item                Gay Marriage  Refugee Allowing  Income Inequality  Gender Role  Climate Change  Gun Regulation  Drug Addiction  Race Diversity  Health Insurance  Average
Group
Ideology                  -0.036            -0.086              0.145        0.900           0.181             NaN             NaN          -0.146               NaN    0.160
Party                     -0.021            -0.109              0.078        0.900           0.211             NaN             NaN          -0.132               NaN    0.154
Political Interest        -0.030            -0.124             -0.200        0.892           0.215             NaN             NaN          -0.145               NaN    0.101
Church                    -0.026            -0.085             -0.146        0.899           0.205             NaN             NaN          -0.137               NaN    0.118
Gender                    -0.026            -0.085             -0.165        0.898           0.206             NaN             NaN          -0.140               NaN    0.115
Age                       -0.031            -0.086             -0.150        0.893           0.204             NaN             NaN          -0.139               NaN    0.115
Race                      -0.013            -0.108             -0.190        0.851           0.195             NaN             NaN          -0.142               NaN    0.099
Discuss Politics          -0.022            -0.111             -0.276        0.886           0.211             NaN             NaN          -0.185               NaN    0.084

delta |D|  |  priming   (negative = improvement)

item                Gay Marriage  Refugee Allowing  Income Inequality  Gender Role  Climate Change  Gun Regulation  Drug Addiction  Race Diversity  Health Insurance  Average
Group
Ideology                   0.006             0.027              0.092        0.013           0.143          -0.001           0.012           0.023             0.082    0.044
Party                      0.010             0.026              0.078        0.005           0.134           0.001           0.004           0.013             0.075    0.038
Political Interest         0.012             0.032              0.068        0.005           0.151           0.030           0.003           0.024             0.070    0.044
Church                    -0.002             0.033              0.072        0.006           0.143           0.029           0.004           0.013             0.076    0.042
Gender                     0.000             0.033              0.077        0.006           0.143           0.027           0.005           0.013             0.077    0.042
Age                        0.001             0.035              0.075        0.006           0.141           0.019           0.005           0.013             0.078    0.041
Race                       0.013             0.041              0.067        0.006           0.125          -0.008           0.003           0.014             0.046    0.034
Discuss Politics           0.006             0.018              0.057        0.004           0.137           0.015           0.005           0.014             0.039    0.033

delta |D|  |  preamble   (negative = improvement)

item                Gay Marriage  Refugee Allowing  Income Inequality  Gender Role  Climate Change  Gun Regulation  Drug Addiction  Race Diversity  Health Insurance  Average
Group
Ideology                   0.051             0.145              0.085        0.009           0.053           0.044           0.012          -0.011             0.188    0.064
Party                      0.048             0.125              0.080        0.003           0.060           0.032           0.004          -0.005             0.185    0.059
Political Interest         0.056             0.156              0.080        0.003           0.062           0.089           0.003           0.005             0.203    0.073
Church                     0.049             0.142              0.069        0.004           0.064           0.070           0.004          -0.005             0.185    0.065
Gender                     0.048             0.143              0.072        0.004           0.063           0.070           0.005          -0.006             0.186    0.065
Age                        0.047             0.144              0.073        0.004           0.062           0.060           0.005          -0.006             0.190    0.064
Race                       0.034             0.133              0.043        0.002           0.050           0.012           0.003          -0.000             0.163    0.049
Discuss Politics           0.038             0.124              0.024        0.003           0.064           0.061           0.005          -0.018             0.157    0.051

In [ ]:
# Subgroup level (no averaging)
pd.set_option("display.max_rows", 300)

print("Baseline signed desirability gap D at Replicate, per subgroup\n")
display(full_baseD(level=True))

for metric, title in [("delta_jsd", "delta JSD"), ("delta_absD", "delta |D|")]:
    for c in CONDITIONS:
        print(f"\n{title}  |  {c}   (negative = improvement)")
        display(full_level(metric, c))

Baseline signed desirability gap D at Replicate, per subgroup

item                                          Gay Marriage  Refugee Allowing  Income Inequality  Gender Role  Climate Change  Gun Regulation  Drug Addiction  Race Diversity  Health Insurance
Group              Category
Ideology           Extremely liberal                 0.083             0.089              0.083        0.007           0.061           0.022           0.146           0.164             0.056
                   Liberal                           0.046             0.110              0.075       -0.082           0.017          -0.086           0.173           0.154             0.080
                   Slightly liberal                  0.073             0.145              0.125       -0.067          -0.031          -0.062           0.273           0.223             0.087
                   Moderate                          0.168             0.383              0.279       -0.044           0.043           0.056           0.323           0.445             0.253
                   Slightly conservative             0.169             0.456              0.382       -0.040           0.182           0.114           0.358           0.524             0.350
                   Conservative                      0.193             0.304              0.230       -0.021           0.209           0.120           0.401           0.627             0.288
                   Extremely conservative            0.212             0.151              0.154       -0.043           0.204           0.117           0.301           0.577             0.208
Party              Strong democrat                   0.145             0.232              0.234       -0.057           0.036           0.121           0.178           0.240             0.164
                   Weak democrat                     0.103             0.294              0.198       -0.067          -0.014           0.051           0.258           0.341             0.144
                   Democrat-leaning indep.           0.125             0.239              0.243       -0.063           0.026           0.197           0.231           0.240             0.231
                   Independent                       0.168             0.476              0.330       -0.060           0.141           0.153           0.399           0.542             0.308
                   Republican-leaning indep.         0.258             0.454              0.280       -0.035           0.206          -0.066           0.399           0.520             0.300
                   Weak republican                   0.168             0.416              0.401       -0.027           0.154           0.060           0.378           0.550             0.339
                   Strong republican                 0.123             0.120              0.008       -0.028           0.153          -0.154           0.365           0.641             0.058
Political Interest Very                              0.122             0.204              0.144       -0.051           0.134           0.029           0.238           0.334             0.134
                   Somewhat                          0.168             0.278              0.220       -0.048           0.072           0.046           0.303           0.430             0.196
                   Not very                          0.167             0.368              0.306       -0.046           0.062           0.067           0.356           0.480             0.243
                   Not at all                        0.129             0.338              0.312       -0.060           0.119           0.087           0.348           0.575             0.279
Church             Attend church                     0.233             0.347              0.317       -0.040           0.142           0.092           0.319           0.481             0.290
                   Does not attend church            0.077             0.232              0.139       -0.055           0.051           0.008           0.285           0.381             0.113
Gender             Man                               0.163             0.288              0.194       -0.049           0.112           0.079           0.300           0.438             0.180
                   Woman                             0.137             0.284              0.247       -0.047           0.078           0.023           0.301           0.423             0.213
Age                18-29                             0.074             0.211              0.129       -0.096           0.094          -0.023           0.256           0.424             0.115
                   30-39                             0.077             0.255              0.151       -0.073           0.100           0.049           0.288           0.381             0.196
                   40-49                             0.118             0.295              0.246       -0.060           0.100           0.047           0.337           0.425             0.173
                   50-59                             0.180             0.321              0.240       -0.033           0.116           0.157           0.340           0.433             0.215
                   60-69                             0.165             0.304              0.236       -0.022           0.060           0.028           0.308           0.424             0.197
                   70+                               0.254             0.291              0.299       -0.021           0.079           0.023           0.282           0.474             0.245
Race               White                             0.149             0.274              0.230       -0.036           0.102           0.069           0.306           0.433             0.214
                   Black                             0.266             0.342              0.194       -0.069           0.090          -0.078           0.275           0.456             0.062
                   Asian                             0.081             0.299              0.232       -0.078           0.064           0.019           0.272           0.422             0.192
                   Native American                   0.105             0.290              0.126       -0.101           0.009          -0.081           0.287           0.340             0.154
                   Hispanic                          0.220             0.404              0.289       -0.073           0.137           0.279           0.320           0.430             0.394
Discuss Politics   Like to discuss politics          0.139             0.264              0.205       -0.047           0.085           0.040           0.296           0.415             0.181
                   Never discuss politics            0.219             0.531              0.444       -0.063           0.167           0.136           0.353           0.600             0.350

delta JSD  |  reformulated   (negative = improvement)

item                                          Gay Marriage  Refugee Allowing  Income Inequality  Gender Role  Climate Change  Gun Regulation  Drug Addiction  Race Diversity  Health Insurance  Average
Group              Category
Ideology           Extremely liberal                -0.016            -0.011              0.037        0.251          -0.005           0.020           0.000          -0.021             0.014    0.030
                   Liberal                           0.000            -0.029              0.049        0.000           0.026           0.027          -0.005          -0.016             0.014    0.007
                   Slightly liberal                 -0.005            -0.010              0.064       -0.062           0.060           0.028          -0.015          -0.046             0.013    0.003
                   Moderate                         -0.022            -0.096              0.027       -0.098          -0.013           0.011          -0.015          -0.064             0.032   -0.026
                   Slightly conservative            -0.012            -0.103              0.001       -0.082          -0.109           0.005          -0.040          -0.125             0.058   -0.045
                   Conservative                      0.007            -0.063              0.051       -0.070          -0.099           0.027          -0.040          -0.154             0.016   -0.036
                   Extremely conservative            0.024            -0.010              0.057       -0.032          -0.139           0.139           0.022           0.004             0.093    0.018
Party              Strong democrat                   0.007            -0.038              0.031       -0.013          -0.009           0.035           0.000          -0.004             0.021    0.003
                   Weak democrat                     0.019            -0.043              0.042       -0.065           0.049          -0.006          -0.004          -0.034             0.036   -0.001
                   Democrat-leaning indep.          -0.005            -0.052              0.031       -0.039           0.011          -0.032           0.000           0.000             0.021   -0.007
                   Independent                       0.014            -0.159              0.046       -0.101          -0.079          -0.007          -0.032          -0.142             0.001   -0.051
                   Republican-leaning indep.        -0.005            -0.152             -0.054       -0.135          -0.123           0.019          -0.040          -0.096             0.032   -0.062
                   Weak republican                   0.013            -0.099              0.002       -0.060          -0.076          -0.007          -0.019          -0.129             0.015   -0.040
                   Strong republican                -0.024             0.029              0.145       -0.001           0.005           0.174           0.001          -0.115             0.045    0.029
Political Interest Very                             -0.008            -0.021              0.045       -0.043          -0.048           0.035          -0.004          -0.043             0.026   -0.007
                   Somewhat                         -0.011            -0.040              0.058       -0.072          -0.041           0.018          -0.021          -0.067             0.030   -0.016
                   Not very                         -0.011            -0.100              0.022       -0.084          -0.015          -0.009          -0.030          -0.082            -0.001   -0.035
                   Not at all                        0.003            -0.047              0.011       -0.063           0.018          -0.006          -0.044          -0.146             0.020   -0.028
Church             Attend church                    -0.004            -0.078              0.023       -0.074          -0.052           0.008          -0.027          -0.102             0.021   -0.032
                   Does not attend church           -0.008            -0.049              0.067       -0.046          -0.011           0.018          -0.021          -0.052             0.025   -0.008
Gender             Man                              -0.008            -0.057              0.043       -0.073          -0.049           0.009          -0.023          -0.089             0.019   -0.025
                   Woman                            -0.005            -0.066              0.052       -0.046          -0.019           0.018          -0.024          -0.061             0.027   -0.014
Age                18-29                             0.004            -0.048              0.092       -0.068          -0.023           0.009          -0.037          -0.072             0.033   -0.012
                   30-39                            -0.010            -0.055              0.068       -0.055          -0.030           0.021          -0.025          -0.034             0.035   -0.009
                   40-49                            -0.009            -0.062              0.048       -0.060          -0.039           0.010          -0.025          -0.068             0.022   -0.020
                   50-59                            -0.011            -0.062              0.044       -0.059          -0.044          -0.008          -0.018          -0.083             0.014   -0.025
                   60-69                            -0.010            -0.073              0.028       -0.044          -0.027           0.016          -0.021          -0.091             0.019   -0.023
                   70+                              -0.011            -0.055              0.017       -0.060          -0.025           0.025          -0.014          -0.086             0.014   -0.022
Race               White                            -0.009            -0.060              0.043       -0.048          -0.042           0.012          -0.024          -0.082             0.023   -0.021
                   Black                            -0.003            -0.053              0.080       -0.069           0.008           0.015          -0.011          -0.083             0.015   -0.011
                   Asian                            -0.000            -0.072              0.048       -0.084           0.000           0.018          -0.023          -0.007             0.034   -0.010
                   Native American                   0.003            -0.053              0.092       -0.080           0.029           0.052          -0.019          -0.005             0.030    0.005
                   Hispanic                         -0.030            -0.105              0.080       -0.070          -0.108          -0.053          -0.035          -0.006            -0.035   -0.040
Discuss Politics   Like to discuss politics         -0.005            -0.053              0.045       -0.065          -0.032           0.018          -0.022          -0.059             0.035   -0.015
                   Never discuss politics           -0.033            -0.190              0.026       -0.103          -0.048          -0.021          -0.024          -0.201            -0.024   -0.069

delta JSD  |  reversed   (negative = improvement)

item                                          Gay Marriage  Refugee Allowing  Income Inequality  Gender Role  Climate Change  Gun Regulation  Drug Addiction  Race Diversity  Health Insurance  Average
Group              Category
Ideology           Extremely liberal                 0.000            -0.018              0.153        0.715           0.087             NaN             NaN          -0.019               NaN    0.153
                   Liberal                          -0.002             0.002              0.128        0.688           0.162             NaN             NaN          -0.021               NaN    0.160
                   Slightly liberal                  0.020            -0.003              0.062        0.734           0.209             NaN             NaN          -0.072               NaN    0.158
                   Moderate                          0.036            -0.096             -0.044        0.743           0.336             NaN             NaN          -0.171               NaN    0.134
                   Slightly conservative             0.100            -0.135             -0.040        0.788           0.427             NaN             NaN          -0.185               NaN    0.159
                   Conservative                      0.159            -0.026              0.169        0.854           0.406             NaN             NaN          -0.278               NaN    0.214
                   Extremely conservative            0.073            -0.020              0.315        0.836           0.182             NaN             NaN          -0.230               NaN    0.193
Party              Strong democrat                  -0.023            -0.038              0.051        0.683           0.162             NaN             NaN          -0.059               NaN    0.129
                   Weak democrat                     0.035            -0.060              0.017        0.702           0.237             NaN             NaN          -0.090               NaN    0.140
                   Democrat-leaning indep.          -0.014            -0.061              0.071        0.698           0.214             NaN             NaN          -0.070               NaN    0.139
                   Independent                       0.053            -0.159             -0.081        0.714           0.352             NaN             NaN          -0.152               NaN    0.121
                   Republican-leaning indep.         0.078            -0.097              0.065        0.752           0.383             NaN             NaN          -0.186               NaN    0.166
                   Weak republican                   0.095            -0.077             -0.095        0.835           0.438             NaN             NaN          -0.175               NaN    0.170
                   Strong republican                 0.109             0.076              0.421        0.870           0.395             NaN             NaN          -0.293               NaN    0.263
Political Interest Very                              0.049            -0.012             -0.017        0.770           0.155             NaN             NaN          -0.112               NaN    0.139
                   Somewhat                          0.061            -0.044             -0.028        0.773           0.256             NaN             NaN          -0.150               NaN    0.145
                   Not very                          0.057            -0.084             -0.061        0.766           0.386             NaN             NaN          -0.168               NaN    0.149
                   Not at all                        0.034            -0.074             -0.054        0.733           0.408             NaN             NaN          -0.173               NaN    0.146
Church             Attend church                     0.087            -0.053             -0.062        0.786           0.313             NaN             NaN          -0.167               NaN    0.151
                   Does not attend church            0.039            -0.036             -0.007        0.767           0.229             NaN             NaN          -0.133               NaN    0.143
Gender             Man                               0.063            -0.048             -0.024        0.773           0.280             NaN             NaN          -0.171               NaN    0.145
                   Woman                             0.056            -0.042             -0.037        0.777           0.257             NaN             NaN          -0.128               NaN    0.147
Age                18-29                             0.045            -0.041              0.004        0.687           0.294             NaN             NaN          -0.149               NaN    0.140
                   30-39                             0.053            -0.042             -0.009        0.728           0.307             NaN             NaN          -0.146               NaN    0.148
                   40-49                             0.049            -0.050             -0.042        0.755           0.297             NaN             NaN          -0.168               NaN    0.140
                   50-59                             0.062            -0.032             -0.036        0.797           0.274             NaN             NaN          -0.142               NaN    0.154
                   60-69                             0.062            -0.058             -0.040        0.847           0.212             NaN             NaN          -0.142               NaN    0.147
                   70+                               0.075            -0.038             -0.057        0.827           0.227             NaN             NaN          -0.149               NaN    0.147
Race               White                             0.058            -0.038             -0.034        0.807           0.263             NaN             NaN          -0.147               NaN    0.151
                   Black                             0.073            -0.068             -0.018        0.696           0.269             NaN             NaN          -0.183               NaN    0.128
                   Asian                             0.063            -0.080             -0.027        0.700           0.298             NaN             NaN          -0.142               NaN    0.135
                   Native American                   0.078            -0.048              0.001        0.665           0.304             NaN             NaN          -0.123               NaN    0.146
                   Hispanic                          0.048            -0.051             -0.059        0.702           0.273             NaN             NaN          -0.160               NaN    0.126
Discuss Politics   Like to discuss politics          0.061            -0.043             -0.027        0.773           0.257             NaN             NaN          -0.142               NaN    0.147
                   Never discuss politics            0.048            -0.120             -0.094        0.716           0.381             NaN             NaN          -0.243               NaN    0.115

delta JSD  |  priming   (negative = improvement)

item                                          Gay Marriage  Refugee Allowing  Income Inequality  Gender Role  Climate Change  Gun Regulation  Drug Addiction  Race Diversity  Health Insurance  Average
Group              Category
Ideology           Extremely liberal                 0.000             0.008              0.047        0.051           0.066           0.020           0.000           0.000             0.034    0.025
                   Liberal                           0.004             0.017              0.056        0.018           0.065          -0.011           0.000           0.008             0.029    0.021
                   Slightly liberal                 -0.013             0.032              0.082        0.051           0.043           0.007           0.000           0.000             0.056    0.029
                   Moderate                         -0.015             0.032              0.061        0.065           0.122           0.009           0.000           0.016             0.054    0.038
                   Slightly conservative             0.013             0.050              0.103        0.093           0.272           0.021           0.000           0.008             0.087    0.072
                   Conservative                     -0.017             0.057              0.078        0.204           0.355           0.007           0.003           0.063             0.028    0.087
                   Extremely conservative           -0.075            -0.022              0.026        0.260           0.395          -0.021           0.069           0.226             0.051    0.101
Party              Strong democrat                   0.003            -0.004              0.013        0.028           0.093          -0.005           0.000           0.006             0.017    0.017
                   Weak democrat                     0.020             0.016              0.046        0.052           0.088           0.007           0.000           0.016             0.052    0.033
                   Democrat-leaning indep.           0.000            -0.010              0.018        0.005           0.055          -0.024           0.000           0.000             0.008    0.006
                   Independent                       0.014            -0.014              0.024        0.073           0.198           0.042           0.000           0.027             0.047    0.046
                   Republican-leaning indep.         0.017             0.029              0.150        0.097           0.239           0.013           0.000           0.047             0.095    0.076
                   Weak republican                   0.013             0.025              0.046        0.138           0.261           0.013           0.016           0.057             0.032    0.067
                   Strong republican                -0.078             0.021              0.052        0.225           0.337          -0.055           0.029           0.099             0.026    0.073
Political Interest Very                             -0.035            -0.008              0.036        0.119           0.116           0.007           0.012           0.007             0.023    0.031
                   Somewhat                         -0.015             0.021              0.035        0.092           0.117           0.002           0.009           0.029             0.021    0.035
                   Not very                          0.004             0.035              0.032        0.099           0.189           0.008           0.005           0.067             0.046    0.054
                   Not at all                        0.008             0.013              0.031        0.133           0.242           0.025           0.000           0.125             0.025    0.067
Church             Attend church                    -0.006             0.020              0.040        0.123           0.169           0.008           0.005           0.016             0.040    0.046
                   Does not attend church           -0.022             0.005              0.023        0.102           0.125           0.004           0.013           0.054             0.022    0.036
Gender             Man                              -0.018             0.011              0.044        0.121           0.152           0.009           0.012           0.032             0.041    0.045
                   Woman                            -0.008             0.014              0.025        0.103           0.141           0.003           0.007           0.043             0.022    0.039
Age                18-29                            -0.007             0.005              0.018        0.094           0.128           0.005           0.014           0.023             0.033    0.035
                   30-39                            -0.017             0.003              0.028        0.108           0.161           0.006           0.006           0.036             0.039    0.041
                   40-49                            -0.005             0.011              0.031        0.089           0.136           0.012           0.015           0.028             0.042    0.040
                   50-59                             0.003             0.050              0.034        0.101           0.170           0.001           0.011           0.042             0.036    0.050
                   60-69                            -0.016            -0.002              0.058        0.124           0.126           0.004           0.003           0.049             0.024    0.041
                   70+                              -0.029             0.018              0.032        0.148           0.141           0.003           0.010           0.043             0.011    0.042
Race               White                            -0.020             0.009              0.040        0.115           0.156           0.008           0.009           0.042             0.036    0.044
                   Black                             0.017             0.033              0.009        0.107           0.127           0.009           0.022           0.000             0.017    0.038
                   Asian                             0.000             0.019              0.027        0.102           0.135           0.001           0.005           0.053             0.044    0.043
                   Native American                  -0.020             0.013              0.013        0.066           0.096           0.003           0.000           0.039             0.030    0.027
                   Hispanic                          0.030             0.064              0.053        0.113           0.162          -0.007           0.000           0.051            -0.051    0.046
Discuss Politics   Like to discuss politics         -0.012             0.020              0.040        0.106           0.141           0.005           0.011           0.033             0.029    0.041
                   Never discuss politics           -0.002            -0.009              0.024        0.077           0.216           0.006           0.010           0.050             0.006    0.042

delta JSD  |  preamble   (negative = improvement)

item                                          Gay Marriage  Refugee Allowing  Income Inequality  Gender Role  Climate Change  Gun Regulation  Drug Addiction  Race Diversity  Health Insurance  Average
Group              Category
Ideology           Extremely liberal                 0.000             0.031              0.051        0.017           0.046           0.035           0.000           0.000             0.043    0.025
                   Liberal                          -0.001             0.037              0.042        0.014           0.031          -0.006           0.000           0.003             0.054    0.019
                   Slightly liberal                  0.004             0.097              0.043        0.051          -0.002          -0.003           0.000          -0.010             0.093    0.030
                   Moderate                          0.021             0.156              0.072        0.044           0.016           0.005           0.000          -0.002             0.138    0.050
                   Slightly conservative             0.036             0.197              0.098        0.041           0.081           0.013           0.000          -0.012             0.242    0.077
                   Conservative                      0.016             0.259              0.096        0.043           0.053           0.013           0.003          -0.040             0.253    0.077
                   Extremely conservative           -0.012             0.153              0.054        0.039           0.041           0.037           0.069          -0.055             0.190    0.057
Party              Strong democrat                   0.010             0.015              0.020        0.015           0.031           0.021           0.000           0.006             0.024    0.016
                   Weak democrat                     0.032             0.084              0.040        0.031           0.002           0.012           0.000          -0.004             0.101    0.033
                   Democrat-leaning indep.           0.000             0.014              0.040        0.005           0.005           0.019           0.000           0.000             0.021    0.012
                   Independent                       0.036             0.114              0.046        0.016           0.018           0.023           0.000          -0.005             0.144    0.044
                   Republican-leaning indep.         0.030             0.147              0.107        0.017           0.044          -0.015           0.000          -0.017             0.265    0.064
                   Weak republican                   0.034             0.184              0.089        0.062           0.060           0.014           0.016          -0.018             0.201    0.071
                   Strong republican                -0.027             0.270              0.060        0.080           0.056          -0.037           0.029          -0.025             0.195    0.067
Political Interest Very                             -0.001             0.077              0.038        0.033           0.021           0.011           0.012          -0.018             0.095    0.030
                   Somewhat                          0.004             0.129              0.035        0.037           0.023           0.006           0.009          -0.034             0.100    0.035
                   Not very                          0.019             0.203              0.054        0.031           0.017           0.016           0.005           0.021             0.195    0.062
                   Not at all                        0.042             0.218              0.064        0.097           0.038           0.034           0.000           0.049             0.210    0.083
Church             Attend church                     0.022             0.146              0.047        0.037           0.030           0.009           0.005          -0.026             0.141    0.046
                   Does not attend church           -0.000             0.119              0.024        0.054           0.014           0.008           0.013          -0.001             0.102    0.037
Gender             Man                               0.006             0.130              0.040        0.036           0.014           0.012           0.012          -0.031             0.115    0.037
                   Woman                             0.016             0.137              0.036        0.055           0.028           0.007           0.007           0.005             0.132    0.047
Age                18-29                             0.011             0.105              0.036        0.036           0.019           0.000           0.014          -0.004             0.093    0.034
                   30-39                             0.001             0.112              0.033        0.034           0.028           0.013           0.006           0.002             0.127    0.040
                   40-49                             0.015             0.155              0.036        0.044           0.037           0.007           0.015          -0.023             0.144    0.048
                   50-59                             0.005             0.161              0.042        0.048           0.025           0.006           0.011          -0.004             0.118    0.046
                   60-69                             0.023             0.122              0.025        0.058           0.004           0.008           0.003          -0.005             0.147    0.043
                   70+                               0.000             0.151              0.048        0.059           0.019           0.008           0.010          -0.037             0.111    0.041
Race               White                             0.007             0.132              0.047        0.045           0.023           0.011           0.009          -0.014             0.129    0.043
                   Black                             0.024             0.177              0.026        0.040           0.021          -0.004           0.022          -0.008             0.071    0.041
                   Asian                             0.012             0.109              0.016        0.045           0.041           0.008           0.005           0.005             0.126    0.041
                   Native American                   0.009             0.154             -0.001        0.018           0.010           0.017           0.000           0.011             0.145    0.040
                   Hispanic                          0.001             0.151              0.017        0.034          -0.012           0.005           0.000           0.004             0.067    0.030
Discuss Politics   Like to discuss politics          0.012             0.134              0.044        0.041           0.022           0.011           0.011          -0.007             0.130    0.044
                   Never discuss politics            0.014             0.161             -0.017        0.004           0.038           0.002           0.010          -0.059             0.108    0.029

delta |D|  |  reformulated   (negative = improvement)

item                                          Gay Marriage  Refugee Allowing  Income Inequality  Gender Role  Climate Change  Gun Regulation  Drug Addiction  Race Diversity  Health Insurance  Average
Group              Category
Ideology           Extremely liberal                -0.011            -0.074             -0.031        0.601           0.001           0.005           0.000          -0.065             0.022    0.050
                   Liberal                           0.000            -0.077             -0.049        0.183           0.042           0.023          -0.001          -0.019             0.023    0.014
                   Slightly liberal                 -0.026            -0.104             -0.068       -0.023           0.144           0.086          -0.020          -0.059             0.034   -0.004
                   Moderate                         -0.056            -0.182             -0.013       -0.008           0.046           0.065          -0.011          -0.034             0.053   -0.016
                   Slightly conservative            -0.045            -0.171             -0.152       -0.009          -0.181          -0.089          -0.058          -0.240             0.081   -0.096
                   Conservative                      0.049            -0.178             -0.014       -0.009          -0.200           0.028          -0.166          -0.393            -0.015   -0.100
                   Extremely conservative            0.110            -0.064              0.047       -0.027          -0.155           0.092          -0.265          -0.392             0.110   -0.060
Party              Strong democrat                   0.003            -0.028              0.021        0.113          -0.028           0.031           0.000          -0.002             0.011    0.013
                   Weak democrat                     0.028            -0.067             -0.016       -0.046           0.137           0.042          -0.002          -0.017             0.070    0.014
                   Democrat-leaning indep.          -0.002            -0.041              0.025       -0.005           0.049          -0.051           0.000           0.000             0.008   -0.002
                   Independent                       0.031            -0.235             -0.038       -0.019          -0.111          -0.037          -0.019          -0.109             0.005   -0.059
                   Republican-leaning indep.        -0.011            -0.302             -0.111       -0.027          -0.184           0.116          -0.042          -0.206             0.084   -0.076
                   Weak republican                   0.035            -0.175             -0.060        0.013          -0.140          -0.004          -0.037          -0.222             0.032   -0.062
                   Strong republican                -0.114             0.031              0.070       -0.022          -0.053          -0.006          -0.247          -0.476             0.061   -0.084
Political Interest Very                             -0.037            -0.102             -0.016        0.052          -0.111          -0.022          -0.084          -0.175             0.032   -0.051
                   Somewhat                         -0.017            -0.095             -0.037        0.004          -0.024          -0.011          -0.066          -0.157             0.049   -0.039
                   Not very                         -0.036            -0.238             -0.095       -0.025           0.017          -0.041          -0.028          -0.124            -0.001   -0.063
                   Not at all                        0.023            -0.243             -0.133       -0.048          -0.043          -0.072          -0.027          -0.158             0.056   -0.071
Church             Attend church                    -0.002            -0.160             -0.055        0.012          -0.139          -0.068          -0.071          -0.175             0.028   -0.070
                   Does not attend church           -0.029            -0.144             -0.033        0.006           0.047           0.061          -0.054          -0.143             0.044   -0.027
Gender             Man                              -0.019            -0.134             -0.021       -0.032          -0.067          -0.072          -0.067          -0.161             0.035   -0.060
                   Woman                            -0.008            -0.167             -0.060        0.042          -0.022           0.020          -0.058          -0.157             0.033   -0.042
Age                18-29                            -0.023            -0.190             -0.020       -0.095          -0.037           0.016          -0.054          -0.114             0.091   -0.047
                   30-39                            -0.013            -0.151              0.013       -0.003          -0.064          -0.035          -0.065          -0.130             0.061   -0.043
                   40-49                            -0.010            -0.172             -0.052        0.013          -0.064          -0.033          -0.062          -0.161             0.031   -0.057
                   50-59                            -0.003            -0.130             -0.068        0.057          -0.092          -0.146          -0.072          -0.177             0.018   -0.068
                   60-69                            -0.023            -0.157             -0.043        0.037           0.024           0.029          -0.069          -0.189             0.030   -0.040
                   70+                              -0.037            -0.120             -0.083        0.027           0.003           0.034          -0.042          -0.175            -0.008   -0.045
Race               White                            -0.017            -0.154             -0.044        0.039          -0.060          -0.060          -0.067          -0.173             0.033   -0.056
                   Black                            -0.001            -0.118             -0.044       -0.061          -0.005           0.000          -0.033          -0.131             0.063   -0.037
                   Asian                             0.020            -0.166             -0.047       -0.066           0.007           0.065          -0.048          -0.107             0.031   -0.035
                   Native American                  -0.052            -0.124             -0.056       -0.087           0.097           0.133          -0.082          -0.134             0.075   -0.026
                   Hispanic                         -0.119            -0.195             -0.024       -0.033          -0.090          -0.217          -0.045          -0.075            -0.080   -0.097
Discuss Politics   Like to discuss politics         -0.004            -0.138             -0.042        0.006          -0.028          -0.004          -0.062          -0.152             0.056   -0.041
                   Never discuss politics           -0.078            -0.287             -0.114       -0.051          -0.148          -0.120          -0.047          -0.180            -0.031   -0.117

delta |D|  |  reversed   (negative = improvement)

item                                          Gay Marriage  Refugee Allowing  Income Inequality  Gender Role  Climate Change  Gun Regulation  Drug Addiction  Race Diversity  Health Insurance  Average
Group              Category
Ideology           Extremely liberal                 0.000            -0.027              0.208        0.903           0.038             NaN             NaN          -0.008               NaN    0.186
                   Liberal                          -0.003            -0.039              0.175        0.830           0.087             NaN             NaN          -0.013               NaN    0.173
                   Slightly liberal                 -0.028            -0.081              0.048        0.862           0.124             NaN             NaN          -0.050               NaN    0.146
                   Moderate                         -0.029            -0.155             -0.122        0.912           0.243             NaN             NaN          -0.145               NaN    0.117
                   Slightly conservative             0.073            -0.212             -0.085        0.921           0.284             NaN             NaN          -0.128               NaN    0.142
                   Conservative                     -0.059            -0.041              0.305        0.958           0.319             NaN             NaN          -0.276               NaN    0.201
                   Extremely conservative           -0.210            -0.049              0.486        0.914           0.173             NaN             NaN          -0.404               NaN    0.152
Party              Strong democrat                  -0.029            -0.026              0.047        0.871           0.085             NaN             NaN          -0.041               NaN    0.151
                   Weak democrat                    -0.052            -0.116              0.077        0.858           0.159             NaN             NaN          -0.068               NaN    0.143
                   Democrat-leaning indep.          -0.011            -0.054              0.141        0.872           0.134             NaN             NaN          -0.047               NaN    0.173
                   Independent                      -0.023            -0.246             -0.309        0.879           0.199             NaN             NaN          -0.103               NaN    0.066
                   Republican-leaning indep.        -0.004            -0.196              0.081        0.931           0.300             NaN             NaN          -0.188               NaN    0.154
                   Weak republican                   0.003            -0.161             -0.205        0.944           0.289             NaN             NaN          -0.156               NaN    0.119
                   Strong republican                -0.029             0.038              0.714        0.942           0.309             NaN             NaN          -0.320               NaN    0.276
Political Interest Very                             -0.022            -0.024             -0.125        0.888           0.130             NaN             NaN          -0.083               NaN    0.127
                   Somewhat                         -0.026            -0.089             -0.123        0.902           0.230             NaN             NaN          -0.129               NaN    0.127
                   Not very                         -0.029            -0.166             -0.289        0.907           0.277             NaN             NaN          -0.192               NaN    0.085
                   Not at all                       -0.044            -0.218             -0.264        0.869           0.222             NaN             NaN          -0.173               NaN    0.065
Church             Attend church                     0.012            -0.076             -0.178        0.918           0.222             NaN             NaN          -0.125               NaN    0.129
                   Does not attend church           -0.063            -0.094             -0.115        0.881           0.189             NaN             NaN          -0.149               NaN    0.108
Gender             Man                              -0.031            -0.090             -0.124        0.899           0.218             NaN             NaN          -0.170               NaN    0.117
                   Woman                            -0.022            -0.080             -0.205        0.898           0.194             NaN             NaN          -0.109               NaN    0.113
Age                18-29                            -0.047            -0.107             -0.066        0.803           0.193             NaN             NaN          -0.128               NaN    0.108
                   30-39                            -0.018            -0.083             -0.148        0.846           0.201             NaN             NaN          -0.150               NaN    0.108
                   40-49                            -0.005            -0.107             -0.185        0.877           0.218             NaN             NaN          -0.164               NaN    0.106
                   50-59                            -0.012            -0.044             -0.146        0.929           0.208             NaN             NaN          -0.128               NaN    0.135
                   60-69                            -0.040            -0.105             -0.168        0.950           0.197             NaN             NaN          -0.140               NaN    0.116
                   70+                              -0.061            -0.071             -0.186        0.952           0.207             NaN             NaN          -0.125               NaN    0.119
Race               White                            -0.052            -0.069             -0.151        0.921           0.211             NaN             NaN          -0.137               NaN    0.121
                   Black                             0.054            -0.136             -0.180        0.850           0.135             NaN             NaN          -0.135               NaN    0.098
                   Asian                             0.048            -0.165             -0.216        0.845           0.212             NaN             NaN          -0.140               NaN    0.098
                   Native American                  -0.036            -0.100             -0.123        0.792           0.183             NaN             NaN          -0.134               NaN    0.097
                   Hispanic                         -0.082            -0.072             -0.280        0.847           0.235             NaN             NaN          -0.162               NaN    0.081
Discuss Politics   Like to discuss politics         -0.029            -0.082             -0.144        0.901           0.205             NaN             NaN          -0.126               NaN    0.121
                   Never discuss politics           -0.014            -0.139             -0.408        0.871           0.216             NaN             NaN          -0.244               NaN    0.047

delta |D|  |  priming   (negative = improvement)

item                                          Gay Marriage  Refugee Allowing  Income Inequality  Gender Role  Climate Change  Gun Regulation  Drug Addiction  Race Diversity  Health Insurance  Average
Group              Category
Ideology           Extremely liberal                 0.000             0.011              0.057        0.082           0.035           0.096           0.000           0.000             0.043    0.036
                   Liberal                           0.004             0.014              0.089        0.006           0.066          -0.056           0.000           0.003             0.038    0.018
                   Slightly liberal                 -0.018             0.054              0.143        0.003           0.051          -0.029           0.000           0.000             0.106    0.035
                   Moderate                         -0.033             0.024              0.088        0.000           0.125           0.027           0.000           0.004             0.063    0.033
                   Slightly conservative             0.040             0.044              0.134        0.000           0.154           0.036           0.000           0.002             0.115    0.058
                   Conservative                      0.024             0.082              0.091        0.000           0.251          -0.008           0.001           0.023             0.064    0.059
                   Extremely conservative            0.025            -0.042              0.043        0.000           0.316          -0.074           0.080           0.128             0.141    0.069
Party              Strong democrat                   0.002            -0.002              0.011        0.016           0.072          -0.011           0.000           0.002             0.010    0.011
                   Weak democrat                     0.025             0.016              0.065        0.009           0.084           0.061           0.000           0.005             0.077    0.038
                   Democrat-leaning indep.           0.000            -0.005              0.015        0.002           0.055          -0.042           0.000           0.000             0.004    0.003
                   Independent                       0.030            -0.018              0.028        0.001           0.113           0.076           0.000           0.008             0.052    0.032
                   Republican-leaning indep.         0.012             0.021              0.152        0.000           0.162          -0.050           0.000           0.017             0.132    0.050
                   Weak republican                   0.023             0.032              0.046        0.002           0.168           0.061           0.009           0.020             0.036    0.044
                   Strong republican                -0.019             0.138              0.231        0.002           0.285          -0.088           0.019           0.040             0.212    0.091
Political Interest Very                             -0.024             0.021              0.096        0.009           0.099           0.048           0.008           0.002             0.087    0.039
                   Somewhat                         -0.012             0.049              0.081        0.002           0.148           0.020           0.005           0.009             0.062    0.040
                   Not very                          0.013             0.042              0.053        0.001           0.172           0.031           0.001           0.029             0.083    0.047
                   Not at all                        0.071             0.017              0.041        0.008           0.183           0.022           0.000           0.058             0.047    0.050
Church             Attend church                     0.009             0.035              0.065        0.002           0.145           0.009           0.002           0.004             0.066    0.037
                   Does not attend church           -0.012             0.031              0.079        0.009           0.140           0.049           0.007           0.023             0.085    0.046
Gender             Man                              -0.012             0.033              0.101        0.004           0.143           0.017           0.006           0.011             0.103    0.045
                   Woman                             0.012             0.033              0.052        0.007           0.142           0.038           0.003           0.015             0.051    0.039
Age                18-29                            -0.011             0.020              0.072        0.006           0.120           0.006           0.007           0.007             0.094    0.036
                   30-39                            -0.010             0.022              0.084        0.008           0.133           0.031           0.002           0.013             0.085    0.041
                   40-49                             0.026             0.029              0.064        0.004           0.137           0.049           0.009           0.009             0.100    0.047
                   50-59                             0.044             0.072              0.066        0.003           0.145          -0.011           0.007           0.016             0.077    0.047
                   60-69                            -0.010             0.015              0.113        0.006           0.155           0.028           0.001           0.020             0.073    0.045
                   70+                              -0.034             0.055              0.050        0.007           0.156           0.011           0.003           0.014             0.036    0.033
Race               White                            -0.008             0.032              0.083        0.006           0.151           0.034           0.005           0.015             0.081    0.044
                   Black                             0.035             0.040              0.026        0.012           0.092          -0.001           0.010           0.000             0.052    0.029
                   Asian                             0.021             0.041              0.065        0.000           0.137          -0.002           0.002           0.020             0.088    0.041
                   Native American                  -0.019             0.027              0.065        0.005           0.124           0.017           0.000           0.015             0.084    0.035
                   Hispanic                          0.037             0.064              0.096        0.008           0.120          -0.088           0.000           0.019            -0.075    0.020
Discuss Politics   Like to discuss politics          0.007             0.048              0.093        0.005           0.145           0.035           0.005           0.011             0.080    0.048
                   Never discuss politics            0.004            -0.011              0.020        0.003           0.129          -0.004           0.005           0.017            -0.001    0.018

delta |D|  |  preamble   (negative = improvement)

item                                          Gay Marriage  Refugee Allowing  Income Inequality  Gender Role  Climate Change  Gun Regulation  Drug Addiction  Race Diversity  Health Insurance  Average
Group              Category
Ideology           Extremely liberal                 0.000             0.023              0.058        0.056           0.031           0.127           0.000           0.000             0.047    0.038
                   Liberal                           0.001             0.023              0.076        0.005           0.048          -0.035           0.000           0.001             0.053    0.019
                   Slightly liberal                  0.013             0.098              0.086        0.003          -0.001          -0.045           0.000          -0.003             0.135    0.032
                   Moderate                          0.028             0.101              0.085        0.000           0.066           0.053           0.000          -0.001             0.151    0.054
                   Slightly conservative             0.084             0.130              0.098       -0.002           0.082           0.070           0.000          -0.004             0.245    0.078
                   Conservative                      0.102             0.304              0.086        0.000           0.082           0.053           0.001          -0.020             0.342    0.106
                   Extremely conservative            0.127             0.339              0.106        0.000           0.063           0.088           0.080          -0.052             0.345    0.122
Party              Strong democrat                   0.004             0.005              0.014        0.014           0.042           0.022           0.000           0.002             0.012    0.013
                   Weak democrat                     0.038             0.053              0.066        0.005           0.023           0.097           0.000          -0.001             0.118    0.044
                   Democrat-leaning indep.           0.000             0.005              0.030        0.002           0.042           0.022           0.000           0.000             0.008    0.012
                   Independent                       0.061             0.068              0.057       -0.001           0.040           0.079           0.000          -0.002             0.137    0.049
                   Republican-leaning indep.         0.038             0.106              0.102        0.000           0.076           0.000           0.000          -0.008             0.314    0.070
                   Weak republican                   0.076             0.152              0.097        0.002           0.089           0.113           0.009          -0.009             0.226    0.084
                   Strong republican                 0.117             0.486              0.192        0.001           0.106          -0.111           0.019          -0.014             0.477    0.141
Political Interest Very                              0.048             0.117              0.078        0.006           0.056           0.080           0.008          -0.007             0.179    0.063
                   Somewhat                          0.033             0.148              0.059        0.000           0.072           0.044           0.005          -0.016             0.166    0.057
                   Not very                          0.043             0.156              0.072        0.000           0.066           0.095           0.001           0.011             0.232    0.075
                   Not at all                        0.099             0.202              0.111        0.008           0.056           0.137           0.000           0.029             0.235    0.097
Church             Attend church                     0.061             0.134              0.067        0.001           0.061           0.051           0.002          -0.010             0.167    0.059
                   Does not attend church            0.037             0.150              0.071        0.007           0.066           0.089           0.007          -0.000             0.204    0.070
Gender             Man                               0.038             0.150              0.079        0.002           0.059           0.071           0.006          -0.015             0.195    0.065
                   Woman                             0.059             0.137              0.064        0.005           0.068           0.069           0.003           0.002             0.177    0.065
Age                18-29                             0.038             0.118              0.111        0.002           0.031           0.045           0.007          -0.001             0.189    0.060
                   30-39                             0.044             0.120              0.085        0.005           0.054           0.080           0.002           0.001             0.190    0.065
                   40-49                             0.069             0.155              0.063        0.004           0.083           0.060           0.009          -0.010             0.223    0.073
                   50-59                             0.046             0.169              0.075        0.003           0.064           0.021           0.007          -0.001             0.176    0.062
                   60-69                             0.067             0.127              0.041        0.005           0.074           0.073           0.001          -0.003             0.205    0.066
                   70+                               0.018             0.175              0.061        0.007           0.067           0.080           0.003          -0.019             0.155    0.061
Race               White                             0.047             0.149              0.083        0.004           0.068           0.068           0.005          -0.007             0.189    0.067
                   Black                             0.045             0.154              0.060        0.010           0.014          -0.059           0.010          -0.002             0.169    0.045
                   Asian                             0.064             0.112              0.042        0.000           0.075           0.070           0.002           0.002             0.183    0.061
                   Native American                   0.024             0.132              0.016       -0.000           0.017          -0.035           0.000           0.004             0.215    0.041
                   Hispanic                         -0.011             0.118              0.011       -0.002           0.078           0.014           0.000           0.002             0.058    0.030
Discuss Politics   Like to discuss politics          0.057             0.150              0.083        0.003           0.069           0.079           0.005          -0.003             0.201    0.072
                   Never discuss politics            0.019             0.098             -0.036        0.003           0.058           0.044           0.005          -0.033             0.114    0.030

In [29]:
# Baseline sign audit, all variables including Age
_b = _full[_full["condition"] == CONDITIONS[0]].dropna(subset=["D_base"])
_neg = _b[_b["D_base"] < 0]

print(f"{len(_neg)} of {len(_b)} subgroup-item cells have D < 0")
print(f"{_b['Category'].nunique()} subgroups, {_b['item'].nunique()} items")
print("\nnegative cells by item (out of subgroups with that item):")
_by = (_neg.groupby("item")["Category"].nunique()
       .to_frame("n_negative")
       .join(_b.groupby("item")["Category"].nunique().rename("n_subgroups"))
       .sort_values("n_negative", ascending=False))
display(_by)

print("\nAge bins with D < 0:")
display(_neg[_neg["Group"] == "Age"][["Category", "item", "D_base"]]
        .sort_values(["item", "Category"]).round(3))

43 of 315 subgroup-item cells have D < 0
35 subgroups, 9 items

negative cells by item (out of subgroups with that item):

                n_negative  n_subgroups
item
Gender Role             34           35
Gun Regulation           7           35
Climate Change           2           35

Age bins with D < 0:

    Category            item  D_base
264    18-29     Gender Role  -0.096
273    30-39     Gender Role  -0.073
282    40-49     Gender Role  -0.060
291    50-59     Gender Role  -0.033
300    60-69     Gender Role  -0.022
309      70+     Gender Role  -0.021
266    18-29  Gun Regulation  -0.023

In [30]:
_b = _full[_full["condition"] == CONDITIONS[0]]
_r = 1 - _b["n_human"] / _b["n_model"]
print(f"human cells smaller by: mean {_r.mean():.1%}, median {_r.median():.1%}, "
      f"range {_r.min():.1%} to {_r.max():.1%}")

# per item, since non-response varies by question
display((1 - _b.groupby("item")["n_human"].sum() / _b.groupby("item")["n_model"].sum())
        .mul(100).round(1).sort_values().to_frame("% smaller"))

human cells smaller by: mean 10.0%, median 12.1%, range -7.4% to 24.4%

                   % smaller
item
Gay Marriage             1.2
Gun Regulation           9.3
Refugee Allowing         9.7
Climate Change           9.8
Income Inequality       10.0
Gender Role             10.4
Race Diversity          10.4
Drug Addiction          10.5
Health Insurance        10.7